services:
  clouddriver-armory:
    baseService: clouddriver
    image:
      imageId: sha256:631fc0c6acbdef40bd9e9b1546b898388c3207ad373ea055f191580910ee02db
      repository: armory/clouddriver-armory
      tag: 2022.09.14.17.01.20.master
    vcs:
      repo:
        orgName: armory-io
        repoName: clouddriver-armory
        type: github
      sha: 8a0b6b34ffcdd4b0b749a0452a339282bedda7eb
  deck-armory:
    baseService: deck
    image:
      imageId: sha256:995fcf657d27ea8ab463e019d71a992bb2257824d7effdbea7649e3aba6dd991
      repository: armory/deck-armory
      tag: 2022.11.30.23.02.51.master
    vcs:
      repo:
        orgName: armory-io
        repoName: deck-armory
        type: github
      sha: 1c1608baa1f636e52fd0a7c27b2c49d00cda8065
  dinghy:
    image:
      imageId: sha256:c66fe5557f46f25b5e7b2a7c75f1993a748ca4dfff1470f636836152ced5fcc3
      repository: armory/dinghy
      tag: 2022.10.27.16.41.18.master
    vcs:
      repo:
        orgName: armory-io
        repoName: dinghy
        type: github
      sha: 505015ac9d2539290af87e9a1e234827905db645
  echo-armory:
    baseService: echo
    image:
      imageId: sha256:253d6cff4c50f2748289df708fc444bb94723b4198865f05d649367723447b65
      repository: armory/echo-armory
      tag: 2022.09.14.16.38.52.master
    vcs:
      repo:
        orgName: armory-io
        repoName: echo-armory
        type: github
      sha: bd39fc4fdbe840755a56b61aded3815b3cd038f0
  fiat-armory:
    baseService: fiat
    image:
      imageId: sha256:0de91d7250463a4cceb1180ff5d0607aa9f684fe12c526ab7e9c0ca9e2f77edd
      repository: armory/fiat-armory
      tag: 2022.12.15.15.45.26.master
    vcs:
      repo:
        orgName: armory-io
        repoName: fiat-armory
        type: github
      sha: 407b59b9d9a8953f5d8e30c1a6380efc3ef7a932
  front50-armory:
    baseService: front50
    image:
      imageId: sha256:1d0dc4de0f08c948bddf1ad1f760981b4f5fff063d19e8853f82227c3880296b
      repository: armory/front50-armory
      tag: 2022.07.08.02.40.47.master
    vcs:
      repo:
        orgName: armory-io
        repoName: front50-armory
        type: github
      sha: b8ea85489ae8ba7f09e93573a364e9ba4c3512fb
  gate-armory:
    baseService: gate
    image:
      imageId: sha256:67b4e14ca1adece5011a8425777bf61630fe0fabeb64d0ef9ab64d47c1ac965e
      repository: armory/gate-armory
      tag: 2022.11.17.22.19.35.master
    vcs:
      repo:
        orgName: armory-io
        repoName: gate-armory
        type: github
      sha: f22b9d124867bb865860e9419a1c9a1e6e910cd6
  igor-armory:
    baseService: igor
    image:
      imageId: sha256:d9498ab90b76c900d305a9cedd2fd65d5a8423a4893f0a5705f78e38b2c00c2f
      repository: armory/igor-armory
      tag: 2022.09.14.16.39.54.master
    vcs:
      repo:
        orgName: armory-io
        repoName: igor-armory
        type: github
      sha: 3c9dd843c3eddbfaa529f054b2df73de938391ca
  kayenta-armory:
    baseService: kayenta
    image:
      imageId: sha256:b9779587cb78760ca62650cad34cc72f23b64a0202a443293530e086e4fd4504
      repository: armory/kayenta-armory
      tag: 2022.08.13.22.55.22.master
    vcs:
      repo:
        orgName: armory-io
        repoName: kayenta-armory
        type: github
      sha: a098bd66155b35f0ab2549cbd3a2f49c2aa817b6
  orca-armory:
    baseService: orca
    image:
      imageId: sha256:8fb5a0a2067bfa1fd3d9aab5d41ac2241b9c8f2bf6fc8c95da7832e1211268a2
      repository: armory/orca-armory
      tag: 2022.12.09.17.44.56.master
    vcs:
      repo:
        orgName: armory-io
        repoName: orca-armory
        type: github
      sha: 7b7b8ee879289d10f9f230930362a83e639d61aa
  rosco-armory:
    baseService: rosco
    image:
      imageId: sha256:0239102d0be64253c18df1bba7657b6eb9cdb4a2c2f40d2a4b2fc32b0c7629ed
      repository: armory/rosco-armory
      tag: 2022.07.20.21.06.26.master
    vcs:
      repo:
        orgName: armory-io
        repoName: rosco-armory
        type: github
      sha: fb245283577bd8d2d699c331a17c98011e260afe
  terraformer:
    baseService: null
    image:
      imageId: sha256:0d0ed4a42d4362f96caf4dc45814abaf1e858b5df1f972135f07e62f8f12df6a
      repository: armory/terraformer
      tag: 2022.08.15.08.23.24.master
    vcs:
      repo:
        orgName: armory-io
        repoName: terraformer
        type: github
      sha: 06274aea2918f7e47222856537224de91c9cf542
