services:
  clouddriver-armory:
    baseService: clouddriver
    image:
      imageId: sha256:b5af26f70e201b553fc2896eac27982b7cc35c14be6e2e2c2c116a16688753d5
      repository: armory/clouddriver-armory
      tag: 2022.03.15.20.31.00.release-2.27.x
    vcs:
      repo:
        orgName: armory-io
        repoName: clouddriver-armory
        type: github
      sha: d83f2cd5980d6676e76088b56bd193af9d69b2df
  deck-armory:
    baseService: deck
    image:
      imageId: sha256:16fe21d06935b1d3dab54dfdc738e77a0767be984e2a63e136f88d126a4bb106
      repository: armory/deck-armory
      tag: 2022.03.16.00.09.32.release-2.27.x
    vcs:
      repo:
        orgName: armory-io
        repoName: deck-armory
        type: github
      sha: a1d92e8651e6148a650f814c1b409e52c8a547ac
  dinghy:
    baseService: null
    image:
      imageId: sha256:c24fa4ab0ace8a0728627dd679133a7d1521d98dd5480d9035f860d2dec6452e
      repository: armory/dinghy
      tag: 2022.01.25.21.39.56.release-2.27.x
    vcs:
      repo:
        orgName: armory-io
        repoName: dinghy
        type: github
      sha: ee2e7f8b9778741dae1a5571cb47ac6c76c51d81
  echo-armory:
    baseService: echo
    image:
      imageId: sha256:ac514afd6b61ddede446b5821731e7743a1155a49bae125c9a09919546d73364
      repository: armory/echo-armory
      tag: 2022.03.10.23.47.30.release-2.27.x
    vcs:
      repo:
        orgName: armory-io
        repoName: echo-armory
        type: github
      sha: 3cc38989c95b9de9dfacad2aef53d02221fd4d8d
  fiat-armory:
    baseService: fiat
    image:
      imageId: sha256:a5c74bed8c0f22efe0c4267d03a7d338fdbd1235d7f5c976c13096750426f0db
      repository: armory/fiat-armory
      tag: 2022.03.17.00.40.20.release-2.27.x
    vcs:
      repo:
        orgName: armory-io
        repoName: fiat-armory
        type: github
      sha: 926a9fb346f1b5ab63070b5288660121a481acb1
  front50-armory:
    baseService: front50
    image:
      imageId: sha256:51a4e4b3eb28fd5d58d2d97ebdfe07793abe197b2ffc785461ed490e635d916a
      repository: armory/front50-armory
      tag: 2022.03.04.04.42.14.release-2.27.x
    vcs:
      repo:
        orgName: armory-io
        repoName: front50-armory
        type: github
      sha: cdb90f4dc3d55c2a5150a3e573b1862cef93816b
  gate-armory:
    baseService: gate
    image:
      imageId: sha256:6213a9fb31d63a3333beef0ac4b8431c89cb3e8f25fcd6c1ae1798c74de6b6d4
      repository: armory/gate-armory
      tag: 2022.03.17.00.41.15.release-2.27.x
    vcs:
      repo:
        orgName: armory-io
        repoName: gate-armory
        type: github
      sha: 8e0c49961209eee90ceddde5bf465911c261f9aa
  igor-armory:
    baseService: igor
    image:
      imageId: sha256:d789b97f2ae5551a68358a1fd7f1fc3c2b5d98dca7b13222d3b7ca3d14144671
      repository: armory/igor-armory
      tag: 2022.03.10.23.49.00.release-2.27.x
    vcs:
      repo:
        orgName: armory-io
        repoName: igor-armory
        type: github
      sha: ee32926edfa62865eba61ec6d23b8fdc4f9c3fe5
  kayenta-armory:
    baseService: kayenta
    image:
      imageId: sha256:f43330f30abcf97d06c4ff29ac13dad76800d1682cb4b1ff1d8bd62f85f2f909
      repository: armory/kayenta-armory
      tag: 2022.02.22.23.20.32.release-2.27.x
    vcs:
      repo:
        orgName: armory-io
        repoName: kayenta-armory
        type: github
      sha: 800b14c9162cc0f486f4e7f510f87ec8db9b5e98
  orca-armory:
    baseService: orca
    image:
      imageId: sha256:8d6e9b3cdec6cd8229dfa9ed7f710a35e8b7df9de7f0835f4e050e0697257b9d
      repository: armory/orca-armory
      tag: 2022.03.10.23.47.14.release-2.27.x
    vcs:
      repo:
        orgName: armory-io
        repoName: orca-armory
        type: github
      sha: 1f260dad8ccdb14b5b30fcb18689d9c6f52b0167
  rosco-armory:
    baseService: rosco
    image:
      imageId: sha256:d0dffd548aeb5c0ada101f485df900dfed4ea5c4bd66f74501edff8a47c994f3
      repository: armory/rosco-armory
      tag: 2022.03.10.23.48.56.release-2.27.x
    vcs:
      repo:
        orgName: armory-io
        repoName: rosco-armory
        type: github
      sha: 293c0f3cdd54acc2a80f9b7b4bf306659be9e103
  terraformer:
    baseService: null
    image:
      imageId: sha256:ecf35a806daa139349aad78d9b702db9871807c2a4998a1b215cf708b9c13e14
      repository: armory/terraformer
      tag: 2021.12.20.16.50.16.release-2.27.x
    vcs:
      repo:
        orgName: armory-io
        repoName: terraformer
        type: github
      sha: 89dd4af83b669d6a12de41611ea0bdf57857dd73
