services:
  clouddriver-armory:
    baseService: clouddriver
    image:
      imageId: sha256:1521e94c4fec2d8308139ad4de43b16d9f6978aeb223ed50ce23469b9f7a6379
      repository: armory/clouddriver-armory
      tag: 2021.09.10.08.25.19.release-2.27.x
    vcs:
      repo:
        orgName: armory-io
        repoName: clouddriver-armory
        type: github
      sha: 717316c46d3f0bd6fcf139eb775068fd7be3f4c1
  deck-armory:
    baseService: deck
    image:
      imageId: sha256:2c261fadb8f22d11e2a07d47b35609fa1dce6b2d05cac8ad590a741e7faed96a
      repository: armory/deck-armory
      tag: 2021.09.09.19.58.29.release-2.27.x
    vcs:
      repo:
        orgName: armory-io
        repoName: deck-armory
        type: github
      sha: 248aa201bd5b586d215e38f217d097e6a354529c
  dinghy:
    baseService: null
    image:
      imageId: sha256:3d7040558f76025a9235de3a01a9ff1bf98abd3884826cc94f3e24d8a2b6b631
      repository: armory/dinghy
      tag: 2021.09.09.19.58.08.release-2.27.x
    vcs:
      repo:
        orgName: armory-io
        repoName: dinghy
        type: github
      sha: 71f2ed003fe6b75d8e4f43e800725f2ff3a8a1fe
  echo-armory:
    baseService: echo
    image:
      imageId: sha256:afa00d24eafb7893e3c9a6f6936f62c7bb571f0ec2183d94b6373933e8f1fed3
      repository: armory/echo-armory
      tag: 2021.09.09.20.08.29.release-2.27.x
    vcs:
      repo:
        orgName: armory-io
        repoName: echo-armory
        type: github
      sha: 41acc4bc67e70610063accc7647c39d72a1e924c
  fiat-armory:
    baseService: fiat
    image:
      imageId: sha256:8b534384c15be0a50d488d4f4794add88a3ddf9b0a16150ef15d9f6e9cdec265
      repository: armory/fiat-armory
      tag: 2021.08.24.00.37.48.release-2.27.x
    vcs:
      repo:
        orgName: armory-io
        repoName: fiat-armory
        type: github
      sha: 5fd6276fdf66b9222edca6dfb2502b55cd69e1b6
  front50-armory:
    baseService: front50
    image:
      imageId: sha256:017d40cb5ed0a2aa5432c29a1039a974f9cd14b4c0c0c6650fb0ce6381cce9ce
      repository: armory/front50-armory
      tag: 2021.08.24.19.28.32.release-2.27.x
    vcs:
      repo:
        orgName: armory-io
        repoName: front50-armory
        type: github
      sha: bcafedc1fa3ddbb2d4dcbab909f0c1c9800b0715
  gate-armory:
    baseService: gate
    image:
      imageId: sha256:e16401eed6241448dd8b58eb1c44f722e029be4a8597a307a8733f836620248b
      repository: armory/gate-armory
      tag: 2021.08.23.23.00.56.release-2.27.x
    vcs:
      repo:
        orgName: armory-io
        repoName: gate-armory
        type: github
      sha: 4df301cf7535632685a7c49ef648fe985250ae0d
  igor-armory:
    baseService: igor
    image:
      imageId: sha256:067b121e76c6b92d5c7c85333328e50aaa5a3798bd75993c58b36f083569e4ba
      repository: armory/igor-armory
      tag: 2021.09.09.20.04.40.release-2.27.x
    vcs:
      repo:
        orgName: armory-io
        repoName: igor-armory
        type: github
      sha: 867cfe3a8e360c6c89194e6ab3e80c956b1d635d
  kayenta-armory:
    baseService: kayenta
    image:
      imageId: sha256:3fe4a35a7628a451ef8cd7c64f7f9ed4d69a417e99c8751b1b5d66c835104c49
      repository: armory/kayenta-armory
      tag: 2021.08.25.23.39.20.release-2.27.x
    vcs:
      repo:
        orgName: armory-io
        repoName: kayenta-armory
        type: github
      sha: bee81afb5aa461c344c4a01f277d73fe25cef7dc
  orca-armory:
    baseService: orca
    image:
      imageId: sha256:7ad48ffcdcc55290edabab11a78039b456722f0e35e2183d7d9cdaa6091e60e6
      repository: armory/orca-armory
      tag: 2021.09.09.20.00.11.release-2.27.x
    vcs:
      repo:
        orgName: armory-io
        repoName: orca-armory
        type: github
      sha: 658d6de1e212cbf30181dd30e86283bccf481004
  rosco-armory:
    baseService: rosco
    image:
      imageId: sha256:f77b6f264bfb9b55695aef140c1792a16039f4af3b719887c63af3d02b996fce
      repository: armory/rosco-armory
      tag: 2021.08.03.20.58.27.release-2.27.x
    vcs:
      repo:
        orgName: armory-io
        repoName: rosco-armory
        type: github
      sha: ff3b0cc47cca46f764c81ef2dee9456ad1b48b8f
  terraformer:
    baseService: null
    image:
      imageId: sha256:7fdcd079c2fef2ac2474a2fb11d4b86d0e25b98d08b390ca208d19e50745b5ea
      repository: armory/terraformer
      tag: 2021.07.15.17.11.22.release-2.27.x
    vcs:
      repo:
        orgName: armory-io
        repoName: terraformer
        type: github
      sha: 717efc9563cee20cb9c37068db976d9598461e1e
