services:
  clouddriver-armory:
    baseService: clouddriver
    image:
      imageId: sha256:c326a4582f02d2d2603285bb6ad58b3db2e00182d58bcf2b1e068def9be84dd9
      repository: armory/clouddriver-armory
      tag: 2022.01.20.22.39.34.release-2.27.x
    vcs:
      repo:
        orgName: armory-io
        repoName: clouddriver-armory
        type: github
      sha: 1ac6c02720bd3a47d668a5717ac72da23d84837b
  deck-armory:
    baseService: deck
    image:
      imageId: sha256:aad9f72602d436ffc7fd1928cf171139ad85c8a8a29f4fec25adfc449ff7cc5d
      repository: armory/deck-armory
      tag: 2022.01.21.15.46.38.release-2.27.x
    vcs:
      repo:
        orgName: armory-io
        repoName: deck-armory
        type: github
      sha: ea911f8927180bb5223f3c6149005568111ad294
  dinghy:
    baseService: null
    image:
      imageId: sha256:c24fa4ab0ace8a0728627dd679133a7d1521d98dd5480d9035f860d2dec6452e
      repository: armory/dinghy
      tag: 2022.01.25.21.39.56.release-2.27.x
    vcs:
      repo:
        orgName: armory-io
        repoName: dinghy
        type: github
      sha: ee2e7f8b9778741dae1a5571cb47ac6c76c51d81
  echo-armory:
    baseService: echo
    image:
      imageId: sha256:d18302e757ab9ecc4f68d4c496ab1423b6918c27ea8a9eec4aef53232d80d7a6
      repository: armory/echo-armory
      tag: 2022.02.08.22.31.51.release-2.27.x
    vcs:
      repo:
        orgName: armory-io
        repoName: echo-armory
        type: github
      sha: 501a4221bfa05e489ebaa5387f722f75900aea70
  fiat-armory:
    baseService: fiat
    image:
      imageId: sha256:d1569bb4e9f7306ee45bb587e8747316dcd8951e9a3a5a56e0ed2c24072a59ae
      repository: armory/fiat-armory
      tag: 2022.01.25.22.07.32.release-2.27.x
    vcs:
      repo:
        orgName: armory-io
        repoName: fiat-armory
        type: github
      sha: 70e9a19bed0e82ba55761c524faf3e270e61345b
  front50-armory:
    baseService: front50
    image:
      imageId: sha256:3650496a5df02e371f4985caaf258591e8869505469e89b2832c566231777e7e
      repository: armory/front50-armory
      tag: 2022.02.08.22.37.39.release-2.27.x
    vcs:
      repo:
        orgName: armory-io
        repoName: front50-armory
        type: github
      sha: 538e0790758e98f92f8a3d454964761e21af7f48
  gate-armory:
    baseService: gate
    image:
      imageId: sha256:256981b515d4a5ac007da30c0635bad6be929b0e0ba83e75cb973aa5fbd6d897
      repository: armory/gate-armory
      tag: 2022.02.03.20.26.47.release-2.27.x
    vcs:
      repo:
        orgName: armory-io
        repoName: gate-armory
        type: github
      sha: 65b0d0a4125d007ae746f9f8eb967f9d4bcfcbc9
  igor-armory:
    baseService: igor
    image:
      imageId: sha256:06a7b7317b8d53d0359ebddbb4d57ef5ba4a126f0434ac0d9e96a5948199a847
      repository: armory/igor-armory
      tag: 2022.02.03.09.47.05.release-2.27.x
    vcs:
      repo:
        orgName: armory-io
        repoName: igor-armory
        type: github
      sha: dff0a0e25ce8a68e5bbaab5aff11de2cb074de73
  kayenta-armory:
    baseService: kayenta
    image:
      imageId: sha256:02de3048227ee47eb1bf10f35058713901ef7c586b20033a24b1f6ce94ff94fb
      repository: armory/kayenta-armory
      tag: 2022.02.03.22.52.49.release-2.27.x
    vcs:
      repo:
        orgName: armory-io
        repoName: kayenta-armory
        type: github
      sha: 37f2ed19817d8b2403185c2dbae8dbd32071c9da
  orca-armory:
    baseService: orca
    image:
      imageId: sha256:8c69efa6efd89a1be1bf5120f6448801177c7ca2bb14842e8c775fd87aa7e44c
      repository: armory/orca-armory
      tag: 2022.02.08.22.28.09.release-2.27.x
    vcs:
      repo:
        orgName: armory-io
        repoName: orca-armory
        type: github
      sha: 540e5efebce7be47ef154d05af279c79292e6ec0
  rosco-armory:
    baseService: rosco
    image:
      imageId: sha256:fe9fa29b27111b28106a7ee019bf90f6b8220ba1f70bafd046788bd75a961c87
      repository: armory/rosco-armory
      tag: 2022.01.17.19.54.17.release-2.27.x
    vcs:
      repo:
        orgName: armory-io
        repoName: rosco-armory
        type: github
      sha: 602bdfa18b93511cbc24fb94c833ab4f4cdb8789
  terraformer:
    baseService: null
    image:
      imageId: sha256:ecf35a806daa139349aad78d9b702db9871807c2a4998a1b215cf708b9c13e14
      repository: armory/terraformer
      tag: 2021.12.20.16.50.16.release-2.27.x
    vcs:
      repo:
        orgName: armory-io
        repoName: terraformer
        type: github
      sha: 89dd4af83b669d6a12de41611ea0bdf57857dd73
