services:
  clouddriver-armory:
    baseService: clouddriver
    image:
      imageId: sha256:0d3e704da45a039baa0f06e6f447dcd8f44ef85b43811d6ff4275651be029634
      repository: armory/clouddriver-armory
      tag: 2021.07.26.15.42.30.master
    vcs:
      repo:
        orgName: armory-io
        repoName: clouddriver-armory
        type: github
      sha: 6ab195fce1233629f520cd1091d7435a5f8cd689
  deck-armory:
    baseService: deck
    image:
      imageId: sha256:5c8f66dedb122438ec78a8ff5b81d6ffda88d655395bff89140197a0980d0037
      repository: armory/deck-armory
      tag: 2021.07.27.18.40.56.master
    vcs:
      repo:
        orgName: armory-io
        repoName: deck-armory
        type: github
      sha: a3fea8bbc600028010d049d3148be27b34536024
  dinghy:
    baseService: null
    image:
      imageId: sha256:fff91a3d1888052faa1fc6fb72b677d6c563c76567266f206abe0aff7c757aab
      repository: armory/dinghy
      tag: 2021.07.19.20.54.25.master
    vcs:
      repo:
        orgName: armory-io
        repoName: dinghy
        type: github
      sha: de5233ec95845206e20f9b969426c2bf35c98d73
  echo-armory:
    baseService: echo
    image:
      imageId: sha256:62089e1f902698e2e368da744ff82545b0a04503f1f471367af5a1a761ddc3c7
      repository: armory/echo-armory
      tag: 2021.07.28.18.08.40.master
    vcs:
      repo:
        orgName: armory-io
        repoName: echo-armory
        type: github
      sha: 363f2790b0a3f48ed11d22df89b826972b368201
  fiat-armory:
    baseService: fiat
    image:
      imageId: sha256:e2255882f29d2a6eeac28742308538319b7d19c68946d210994b99d420c1b78d
      repository: armory/fiat-armory
      tag: 2021.06.25.20.06.22.master
    vcs:
      repo:
        orgName: armory-io
        repoName: fiat-armory
        type: github
      sha: d79c0d0cdbd9fc68a65a2b7ee391df0406af8110
  front50-armory:
    baseService: front50
    image:
      imageId: sha256:d78a78e084ce7619e6b92a4e3ee69db4095d1b92f9dbf240b251231fd4f162f6
      repository: armory/front50-armory
      tag: 2021.07.27.04.36.03.master
    vcs:
      repo:
        orgName: armory-io
        repoName: front50-armory
        type: github
      sha: ce6e076764debb36432650838819eee8226935d2
  gate-armory:
    baseService: gate
    image:
      imageId: sha256:6d1e9f953675ea60063ec11e7986a89db8467d0ffcf4fdfd3cc8191b6a724836
      repository: armory/gate-armory
      tag: 2021.06.25.20.09.46.master
    vcs:
      repo:
        orgName: armory-io
        repoName: gate-armory
        type: github
      sha: 19284cdbaa403233893da111d46d1b1a1cdec0b1
  igor-armory:
    baseService: igor
    image:
      imageId: sha256:dfca47bce3c79b545f79f8304ee6857143f6a40d51529605ce38c662b9e66216
      repository: armory/igor-armory
      tag: 2021.07.27.05.09.08.master
    vcs:
      repo:
        orgName: armory-io
        repoName: igor-armory
        type: github
      sha: d0b897f67bad90e81dcc0ec3d15c21f1ea6669b1
  kayenta-armory:
    baseService: kayenta
    image:
      imageId: sha256:152413ad8e52ec829141c603ae94f4d65f6d65ce57b457876bbcc6ef2aeadf29
      repository: armory/kayenta-armory
      tag: 2021.07.21.22.52.32.master
    vcs:
      repo:
        orgName: armory-io
        repoName: kayenta-armory
        type: github
      sha: fd91290091563b96ad5973860e7858ae7d63292e
  orca-armory:
    baseService: orca
    image:
      imageId: sha256:2f5beb745fed975c60a9b175379875bb4a28428144c58f448202740e35b20367
      repository: armory/orca-armory
      tag: 2021.07.28.03.15.55.master
    vcs:
      repo:
        orgName: armory-io
        repoName: orca-armory
        type: github
      sha: 32bf81b297efb35626d07ba05086923bb96be256
  rosco-armory:
    baseService: rosco
    image:
      imageId: sha256:61aeeb7a68daec6f07e28bd1ecd97a8ecb6ef5bc6ca5eb142917db9747dc2603
      repository: armory/rosco-armory
      tag: 2021.07.21.22.38.02.master
    vcs:
      repo:
        orgName: armory-io
        repoName: rosco-armory
        type: github
      sha: 42103e208c025e1cba26bc818dd17139458689f4
  terraformer:
    baseService: null
    image:
      imageId: sha256:647ebb06bdbf9bcd84ffd4f95ad790e9236eaea0258883427d62a9b1fd82940c
      repository: armory/terraformer
      tag: 2021.07.15.17.11.22.master
    vcs:
      repo:
        orgName: armory-io
        repoName: terraformer
        type: github
      sha: 717efc9563cee20cb9c37068db976d9598461e1e
