services:
  clouddriver-armory:
    baseService: clouddriver
    image:
      imageId: sha256:78a143ce572fc40e955b5d0eefce96301b1c21ac063522e0067a758d7796d75b
      repository: armory/clouddriver-armory
      tag: 2023.03.18.00.21.35.master
    vcs:
      repo:
        orgName: armory-io
        repoName: clouddriver-armory
        type: github
      sha: c4d9a05349937fa04d368b863d48a70885c470c5
  deck-armory:
    baseService: deck
    image:
      imageId: sha256:c0e97a3357b870db185b136b602b8f744f433c30d26a1830fa16fbb218dcde45
      repository: armory/deck-armory
      tag: 2023.02.20.13.55.59.master
    vcs:
      repo:
        orgName: armory-io
        repoName: deck-armory
        type: github
      sha: 4e2541bb15f06ce8b1e4e2b0c6356207a1faaa35
  dinghy:
    image:
      imageId: sha256:40a7e7b7e5234a369b646a6c1dbceaf87f66e0537e150204fe3ae1e0360ecb29
      repository: armory/dinghy
      tag: 2023.03.08.19.45.23.master
    vcs:
      repo:
        orgName: armory-io
        repoName: dinghy
        type: github
      sha: 5250de80948732c8caac6ffc5293a8af80a63a0f
  echo-armory:
    baseService: echo
    image:
      imageId: sha256:d5518c6ad0d93f45cd181567b688f672029e845e802529e60f987be5e4b1d5d8
      repository: armory/echo-armory
      tag: 2023.02.20.21.18.14.master
    vcs:
      repo:
        orgName: armory-io
        repoName: echo-armory
        type: github
      sha: 1a368a8dba383bfe661ae55a51db71a9edf5a595
  fiat-armory:
    baseService: fiat
    image:
      imageId: sha256:67fd5d9e5a4cfb93829ca59ea8cdbc34b5c7642df903daefacb7b67634a648bd
      repository: armory/fiat-armory
      tag: 2023.02.20.20.00.50.master
    vcs:
      repo:
        orgName: armory-io
        repoName: fiat-armory
        type: github
      sha: af81ca00fba193cfe464dad7e776c7eb4fc2d83f
  front50-armory:
    baseService: front50
    image:
      imageId: sha256:1d0dc4de0f08c948bddf1ad1f760981b4f5fff063d19e8853f82227c3880296b
      repository: armory/front50-armory
      tag: 2022.07.08.02.40.47.master
    vcs:
      repo:
        orgName: armory-io
        repoName: front50-armory
        type: github
      sha: b8ea85489ae8ba7f09e93573a364e9ba4c3512fb
  gate-armory:
    baseService: gate
    image:
      imageId: sha256:67b4e14ca1adece5011a8425777bf61630fe0fabeb64d0ef9ab64d47c1ac965e
      repository: armory/gate-armory
      tag: 2022.11.17.22.19.35.master
    vcs:
      repo:
        orgName: armory-io
        repoName: gate-armory
        type: github
      sha: f22b9d124867bb865860e9419a1c9a1e6e910cd6
  igor-armory:
    baseService: igor
    image:
      imageId: sha256:d9498ab90b76c900d305a9cedd2fd65d5a8423a4893f0a5705f78e38b2c00c2f
      repository: armory/igor-armory
      tag: 2022.09.14.16.39.54.master
    vcs:
      repo:
        orgName: armory-io
        repoName: igor-armory
        type: github
      sha: 3c9dd843c3eddbfaa529f054b2df73de938391ca
  kayenta-armory:
    baseService: kayenta
    image:
      imageId: sha256:c4b9f8fc12d74ceb877f4949a6faa02bbbbb607203991b1f57120cdaa126fb90
      repository: armory/kayenta-armory
      tag: 2023.01.24.16.36.23.master
    vcs:
      repo:
        orgName: armory-io
        repoName: kayenta-armory
        type: github
      sha: ff12c509aec3f18ebf6b817dd260be10297ab241
  orca-armory:
    baseService: orca
    image:
      imageId: sha256:7dd8db31a4b57ea8b1ccfac9cdaeea381e34d3175d94f79715268e8a97769617
      repository: armory/orca-armory
      tag: 2023.04.01.03.03.50.master
    vcs:
      repo:
        orgName: armory-io
        repoName: orca-armory
        type: github
      sha: 7667814bf54c0392d170c7b02c383b996f9d2160
  rosco-armory:
    baseService: rosco
    image:
      imageId: sha256:0239102d0be64253c18df1bba7657b6eb9cdb4a2c2f40d2a4b2fc32b0c7629ed
      repository: armory/rosco-armory
      tag: 2022.07.20.21.06.26.master
    vcs:
      repo:
        orgName: armory-io
        repoName: rosco-armory
        type: github
      sha: fb245283577bd8d2d699c331a17c98011e260afe
  terraformer:
    image:
      imageId: sha256:4b445cd48893742a41444f8bdee91cb5ce3ba49d3d9c8d4f1d496b03bc3f3ff6
      repository: armory/terraformer
      tag: 2023.01.05.16.17.47.master
    vcs:
      repo:
        orgName: armory-io
        repoName: terraformer
        type: github
      sha: 418546f57129380e383e62b6178ed582e6d64a93
