services:
  clouddriver-armory:
    baseService: clouddriver
    image:
      imageId: sha256:feca1b9adcb14d3cbf86b6882aa67bf27e2e6805c53078f14a710a49d70ab08c
      repository: armory/clouddriver-armory
      tag: 2023.01.30.19.04.27.release-2.28.x
    vcs:
      repo:
        orgName: armory-io
        repoName: clouddriver-armory
        type: github
      sha: d52c864053d77a05eef806926591427bc866b529
  deck-armory:
    baseService: deck
    image:
      imageId: sha256:24bcef6bcff23a9e673681a09e6ddbaedc693f5e853a869190c2d075a55892fc
      repository: armory/deck-armory
      tag: 2023.02.03.16.46.18.release-2.28.x
    vcs:
      repo:
        orgName: armory-io
        repoName: deck-armory
        type: github
      sha: bd57caffcdc86c9fb7560e958ba89141372d5d3d
  dinghy:
    image:
      imageId: sha256:a8f210423b9b1ceec1827fc184c9b298fbdb55fcd5f6f841bb1a354c71c5c1cd
      repository: armory/dinghy
      tag: 2022.12.08.13.48.09.release-2.28.x
    vcs:
      repo:
        orgName: armory-io
        repoName: dinghy
        type: github
      sha: c4ed5b19dbcfefe8dea14cdff7df9a8ab540eba3
  echo-armory:
    baseService: echo
    image:
      imageId: sha256:55488757334cdbb5206452525c18f91898205d8d20441fb48c26595184ffa0ec
      repository: armory/echo-armory
      tag: 2023.01.20.16.22.48.release-2.28.x
    vcs:
      repo:
        orgName: armory-io
        repoName: echo-armory
        type: github
      sha: 53bebfd6900b3de124dde043a00d164aa2e50773
  fiat-armory:
    baseService: fiat
    image:
      imageId: sha256:4bdd475a9aa16b2d2682b3ddc78b990e79598d101be326d044ecba46701b0c16
      repository: armory/fiat-armory
      tag: 2022.12.13.21.00.40.release-2.28.x
    vcs:
      repo:
        orgName: armory-io
        repoName: fiat-armory
        type: github
      sha: 48c8759b0878fd1b86b91dae9ee288afcf03dd39
  front50-armory:
    baseService: front50
    image:
      imageId: sha256:f587f52a141ffa3b5dac6688744b4782287b6136839f999181d558d8e846bfa8
      repository: armory/front50-armory
      tag: 2022.12.09.13.31.58.release-2.28.x
    vcs:
      repo:
        orgName: armory-io
        repoName: front50-armory
        type: github
      sha: fab8841982330e7537629c9f24f41205cd5863fd
  gate-armory:
    baseService: gate
    image:
      imageId: sha256:f8e03bbacca701c8bf297c5d0ba47cfb181fca05bd92055d9a3fb52ac10fef6e
      repository: armory/gate-armory
      tag: 2022.12.01.03.50.54.release-2.28.x
    vcs:
      repo:
        orgName: armory-io
        repoName: gate-armory
        type: github
      sha: 65bdd30238312bbca2dce613825eda7ae88f1dfa
  igor-armory:
    baseService: igor
    image:
      imageId: sha256:51aa1f04074378b46714e3103f3df21fd95624879f76793be78b3dc33e354d93
      repository: armory/igor-armory
      tag: 2022.11.29.22.25.00.release-2.28.x
    vcs:
      repo:
        orgName: armory-io
        repoName: igor-armory
        type: github
      sha: 61ce26babfcd0bdf62872c24e707ca5b5371a381
  kayenta-armory:
    baseService: kayenta
    image:
      imageId: sha256:af024d71f2edb7cc8543bf6657faffee660a02eb3e574804b54acde8bd9cc6b6
      repository: armory/kayenta-armory
      tag: 2022.12.16.05.57.53.release-2.28.x
    vcs:
      repo:
        orgName: armory-io
        repoName: kayenta-armory
        type: github
      sha: 0333b9ed6153acfc090edcfa38e3514439e2863c
  orca-armory:
    baseService: orca
    image:
      imageId: sha256:bc640b0e1238e73e767f50bde0162db5da4cd259b6062414008f2d28df25d5a4
      repository: armory/orca-armory
      tag: 2023.02.03.15.22.10.release-2.28.x
    vcs:
      repo:
        orgName: armory-io
        repoName: orca-armory
        type: github
      sha: 37f945ea4ca839267ddd95e436912ef8f82d559e
  rosco-armory:
    baseService: rosco
    image:
      imageId: sha256:6506612f316494a25f4c408fdd28c06b8ea1d0eca0abf2e7c2835a4e6f8f1500
      repository: armory/rosco-armory
      tag: 2022.12.08.22.01.17.release-2.28.x
    vcs:
      repo:
        orgName: armory-io
        repoName: rosco-armory
        type: github
      sha: 945f21dec252da7dd2e00c8d23a1687aa3b9841a
  terraformer:
    image:
      imageId: sha256:8bf86f7296b153e1d8c80a5819ee430b2753e0061e21919d391c615ab6e1bb5f
      repository: armory/terraformer
      tag: 2023.01.05.17.37.01.release-2.28.x
    vcs:
      repo:
        orgName: armory-io
        repoName: terraformer
        type: github
      sha: 3764e523e17dfdd4cf309dc2bd7c13d9b804f309
