services:
  clouddriver-armory:
    baseService: clouddriver
    image:
      imageId: sha256:f7c1e37b07f3d3df391d1ce79b622bb61a8c41cb7901f440f008ef4eb0fdd90f
      repository: armory/clouddriver-armory
      tag: 2021.07.22.20.10.42.master
    vcs:
      repo:
        orgName: armory-io
        repoName: clouddriver-armory
        type: github
      sha: ae91e79a62c5ff98ad227b8ab54c3d7ac0aea54d
  deck-armory:
    baseService: deck
    image:
      imageId: sha256:6c91c65f6695e9752a61ab6180bba378c914b18473908979e1969aa66b4075cf
      repository: armory/deck-armory
      tag: 2021.07.19.22.41.04.master
    vcs:
      repo:
        orgName: armory-io
        repoName: deck-armory
        type: github
      sha: 0cd0ec70b2124fec0b0f542b6c8d7eea8a7641f7
  dinghy:
    baseService: null
    image:
      imageId: sha256:000593ddb37cfd6e8e9aa5cfe2eb7a8962229fe80f5740153f5e62d196fb1417
      repository: armory/dinghy
      tag: 2021.06.22.18.41.16.master
    vcs:
      repo:
        orgName: armory-io
        repoName: dinghy
        type: github
      sha: 7f58e8dd4d34c0251b1d13acd8a5dfc707a487c6
  echo-armory:
    baseService: echo
    image:
      imageId: sha256:f889baeb589fd11c7a0d6215ced4f587c51a5c85536484d6908cd1205c5916d5
      repository: armory/echo-armory
      tag: 2021.06.28.14.49.37.master
    vcs:
      repo:
        orgName: armory-io
        repoName: echo-armory
        type: github
      sha: f64e810f8b7863f27af72d73c0715a91f79f9ce7
  fiat-armory:
    baseService: fiat
    image:
      imageId: sha256:e2255882f29d2a6eeac28742308538319b7d19c68946d210994b99d420c1b78d
      repository: armory/fiat-armory
      tag: 2021.06.25.20.06.22.master
    vcs:
      repo:
        orgName: armory-io
        repoName: fiat-armory
        type: github
      sha: d79c0d0cdbd9fc68a65a2b7ee391df0406af8110
  front50-armory:
    baseService: front50
    image:
      imageId: sha256:a6395f13b5bc93627b2a6aa56630b77a494a787fe2e09a21c232fa700cc9a2f2
      repository: armory/front50-armory
      tag: 2021.06.11.20.05.05.master
    vcs:
      repo:
        orgName: armory-io
        repoName: front50-armory
        type: github
      sha: b9a03c0d3379283a1701fd25bd3c716d68057ed6
  gate-armory:
    baseService: gate
    image:
      imageId: sha256:6d1e9f953675ea60063ec11e7986a89db8467d0ffcf4fdfd3cc8191b6a724836
      repository: armory/gate-armory
      tag: 2021.06.25.20.09.46.master
    vcs:
      repo:
        orgName: armory-io
        repoName: gate-armory
        type: github
      sha: 19284cdbaa403233893da111d46d1b1a1cdec0b1
  igor-armory:
    baseService: igor
    image:
      imageId: sha256:832f3d9965cfca91abb3ce541d2fee93e74c943417c341224c6531f523269dd0
      repository: armory/igor-armory
      tag: 2021.06.29.07.01.07.master
    vcs:
      repo:
        orgName: armory-io
        repoName: igor-armory
        type: github
      sha: f4010629377b626c666b77edee082f379dba1672
  kayenta-armory:
    baseService: kayenta
    image:
      imageId: sha256:152413ad8e52ec829141c603ae94f4d65f6d65ce57b457876bbcc6ef2aeadf29
      repository: armory/kayenta-armory
      tag: 2021.07.21.22.52.32.master
    vcs:
      repo:
        orgName: armory-io
        repoName: kayenta-armory
        type: github
      sha: fd91290091563b96ad5973860e7858ae7d63292e
  orca-armory:
    baseService: orca
    image:
      imageId: sha256:50d9d20565743722e5b7df94f5df710cacd3b61e771f097b38322107ba8f9837
      repository: armory/orca-armory
      tag: 2021.07.21.20.01.30.master
    vcs:
      repo:
        orgName: armory-io
        repoName: orca-armory
        type: github
      sha: 74dcaf639c6c51ffee0f5c5d9fe809e4cb06600e
  rosco-armory:
    baseService: rosco
    image:
      imageId: sha256:61aeeb7a68daec6f07e28bd1ecd97a8ecb6ef5bc6ca5eb142917db9747dc2603
      repository: armory/rosco-armory
      tag: 2021.07.21.22.38.02.master
    vcs:
      repo:
        orgName: armory-io
        repoName: rosco-armory
        type: github
      sha: 42103e208c025e1cba26bc818dd17139458689f4
  terraformer:
    baseService: null
    image:
      imageId: sha256:647ebb06bdbf9bcd84ffd4f95ad790e9236eaea0258883427d62a9b1fd82940c
      repository: armory/terraformer
      tag: 2021.07.15.17.11.22.master
    vcs:
      repo:
        orgName: armory-io
        repoName: terraformer
        type: github
      sha: 717efc9563cee20cb9c37068db976d9598461e1e
