services:
  clouddriver-armory:
    baseService: clouddriver
    image:
      imageId: sha256:d6a3ab4e93b12148aa3e00a370bd07fa47019f55ce5bccb9257b2700cc0ee9ac
      repository: armory/clouddriver-armory
      tag: 2022.02.22.21.11.26.release-2.26.x
    vcs:
      repo:
        orgName: armory-io
        repoName: clouddriver-armory
        type: github
      sha: e0f6e606f758b4f799fddf754ba93646e4fd19e9
  deck-armory:
    baseService: deck
    image:
      imageId: sha256:fde6b765b92d298bf266ef07d2f5353cbd0683e82edaf44b64c7640679a16ba9
      repository: armory/deck-armory
      tag: 2022.01.25.21.35.37.release-2.26.x
    vcs:
      repo:
        orgName: armory-io
        repoName: deck-armory
        type: github
      sha: 621a865a6130cd00e5bd4dbe2416d0d33be98c37
  dinghy:
    baseService: null
    image:
      imageId: sha256:298a4b593181ef4dd9428bd646a0f08e54a3ba11db8794381323ddfb7c91c25c
      repository: armory/dinghy
      tag: 2022.01.25.21.40.03.release-2.26.x
    vcs:
      repo:
        orgName: armory-io
        repoName: dinghy
        type: github
      sha: a6248311be12901a4fc8f5a3e0fae437b4347ce3
  echo-armory:
    baseService: echo
    image:
      imageId: sha256:f1e0f16da5279101e0f359aa7b88f4b8b9cfdef6aba3b761fa41e744d3b1e4fc
      repository: armory/echo-armory
      tag: 2022.01.25.21.41.06.release-2.26.x
    vcs:
      repo:
        orgName: armory-io
        repoName: echo-armory
        type: github
      sha: 9e35502b409fc4191b3cb87332c4138e9b25edf5
  fiat-armory:
    baseService: fiat
    image:
      imageId: sha256:76ef56f7b822e94691ae170b31d3e66eb86fcb1c6d6d3b1a3f51617337ea2f09
      repository: armory/fiat-armory
      tag: 2022.02.03.09.19.15.release-2.26.x
    vcs:
      repo:
        orgName: armory-io
        repoName: fiat-armory
        type: github
      sha: 535b4ebae507de569eb791c2db23ea62fbc5b116
  front50-armory:
    baseService: front50
    image:
      imageId: sha256:91735a57e61e7629231cfc0ef4a847fe061512e7645acd61580ed3401ae26711
      repository: armory/front50-armory
      tag: 2021.10.01.21.33.11.release-2.26.x
    vcs:
      repo:
        orgName: armory-io
        repoName: front50-armory
        type: github
      sha: 7e14c30538a9b97468aba0360408abf4a06bc0dd
  gate-armory:
    baseService: gate
    image:
      imageId: sha256:63e8ab4dfea1913ec283f7ab3ddb8d4e5887db7470087b395ddf172a881eb133
      repository: armory/gate-armory
      tag: 2022.02.17.22.36.16.release-2.26.x
    vcs:
      repo:
        orgName: armory-io
        repoName: gate-armory
        type: github
      sha: 4359026c3e41df10e2b3f81c60ccb44e036b517f
  igor-armory:
    baseService: igor
    image:
      imageId: sha256:0ddb80ee7dd2297d683fe34846f07d0a8419722480d79503a2e1df163e56d1b7
      repository: armory/igor-armory
      tag: 2022.01.25.21.58.17.release-2.26.x
    vcs:
      repo:
        orgName: armory-io
        repoName: igor-armory
        type: github
      sha: f705bacda745f08fa93629c7412e644a5ba22043
  kayenta-armory:
    baseService: kayenta
    image:
      imageId: sha256:ee6be4b5f51d157e092eba84b5094025d82dae2d0e4c44acad8b5ad8616d7f83
      repository: armory/kayenta-armory
      tag: 2022.02.03.22.53.22.release-2.26.x
    vcs:
      repo:
        orgName: armory-io
        repoName: kayenta-armory
        type: github
      sha: 76540e354b3f0784a68d015dc857c25a9a45c76d
  orca-armory:
    baseService: orca
    image:
      imageId: sha256:5f60a34819505e8df2e83d5521bcc43f4a538689b334b72c0ab127ad07949054
      repository: armory/orca-armory
      tag: 2022.01.25.22.03.00.release-2.26.x
    vcs:
      repo:
        orgName: armory-io
        repoName: orca-armory
        type: github
      sha: 557b2d59b42e29adad21a404e38892e701649268
  rosco-armory:
    baseService: rosco
    image:
      imageId: sha256:1cb7532ea4e0aae7b75113465a160fea8c23f657a9ea7ff5a80251e962638b18
      repository: armory/rosco-armory
      tag: 2022.02.19.00.49.37.release-2.26.x
    vcs:
      repo:
        orgName: armory-io
        repoName: rosco-armory
        type: github
      sha: 02d4d0eb9b99a27e2d536cb096173e152f29b986
  terraformer:
    baseService: null
    image:
      imageId: sha256:fc028dea9f74e1dd5f21f9c70d6469180796ab2be72c084c5eac83b05b8a2881
      repository: armory/terraformer
      tag: 2021.12.20.16.50.22.release-2.26.x
    vcs:
      repo:
        orgName: armory-io
        repoName: terraformer
        type: github
      sha: 0cded7056eeecbb85a70a1b94fe1ce83613295bf
