services:
  clouddriver-armory:
    baseService: clouddriver
    image:
      imageId: sha256:ac46033f5a3fe97f450ab732e63ed6d2578af0f17fa04bfdd831c2794412a512
      repository: armory/clouddriver-armory
      tag: 2022.04.26.21.37.57.release-2.27.x
    vcs:
      repo:
        orgName: armory-io
        repoName: clouddriver-armory
        type: github
      sha: 6b717a17d201f456a4b4699991e66a6d2bf2572e
  deck-armory:
    baseService: deck
    image:
      imageId: sha256:3a6a4954d5281c031105c3d7668e01c0346846f9a80fa8842d8310767cf810a7
      repository: armory/deck-armory
      tag: 2022.04.26.15.45.19.release-2.27.x
    vcs:
      repo:
        orgName: armory-io
        repoName: deck-armory
        type: github
      sha: 93be01737b46c03b338459b39083dbd0efd90121
  dinghy:
    baseService: null
    image:
      imageId: sha256:c24fa4ab0ace8a0728627dd679133a7d1521d98dd5480d9035f860d2dec6452e
      repository: armory/dinghy
      tag: 2022.01.25.21.39.56.release-2.27.x
    vcs:
      repo:
        orgName: armory-io
        repoName: dinghy
        type: github
      sha: ee2e7f8b9778741dae1a5571cb47ac6c76c51d81
  echo-armory:
    baseService: echo
    image:
      imageId: sha256:eabf45e8f3c0c0b85c0f245b89eba747abf2c3b2e418a9bd2460db96b4d4c861
      repository: armory/echo-armory
      tag: 2022.04.26.16.35.09.release-2.27.x
    vcs:
      repo:
        orgName: armory-io
        repoName: echo-armory
        type: github
      sha: f5c8db83fa373bf768c3bf03b3b912ba10b0075a
  fiat-armory:
    baseService: fiat
    image:
      imageId: sha256:4685c6d1817ce036126e8b4c86baee96ac52187222553c9fd2c8ae8f201cad71
      repository: armory/fiat-armory
      tag: 2022.04.26.17.13.08.release-2.27.x
    vcs:
      repo:
        orgName: armory-io
        repoName: fiat-armory
        type: github
      sha: d77db2d0ab7cecf42aed2bf750b83e552aa75ae8
  front50-armory:
    baseService: front50
    image:
      imageId: sha256:f081d3532759c697d21b3ccd12054369aaa296812f9fbc108bdfbfea1f434dcd
      repository: armory/front50-armory
      tag: 2022.04.26.21.55.34.release-2.27.x
    vcs:
      repo:
        orgName: armory-io
        repoName: front50-armory
        type: github
      sha: d574051e8541cd5b0f80f0927f5d5631d29355d5
  gate-armory:
    baseService: gate
    image:
      imageId: sha256:be6be3830a1ed4e2f5e6505cf421b102b1acdd4661ac9a37e732894e04a4d4a4
      repository: armory/gate-armory
      tag: 2022.04.26.21.36.23.release-2.27.x
    vcs:
      repo:
        orgName: armory-io
        repoName: gate-armory
        type: github
      sha: b139b70d9e376c85c2c3e159b59d17de4b57b10e
  igor-armory:
    baseService: igor
    image:
      imageId: sha256:c8c83dc7ca0bf7a000f0350075b7a9d68e5e468a0d442a64442a95a3a01fb94f
      repository: armory/igor-armory
      tag: 2022.04.26.17.19.15.release-2.27.x
    vcs:
      repo:
        orgName: armory-io
        repoName: igor-armory
        type: github
      sha: 1dbf04071495d186f7dbc534ed8c01e68950d29e
  kayenta-armory:
    baseService: kayenta
    image:
      imageId: sha256:f43330f30abcf97d06c4ff29ac13dad76800d1682cb4b1ff1d8bd62f85f2f909
      repository: armory/kayenta-armory
      tag: 2022.02.22.23.20.32.release-2.27.x
    vcs:
      repo:
        orgName: armory-io
        repoName: kayenta-armory
        type: github
      sha: 800b14c9162cc0f486f4e7f510f87ec8db9b5e98
  orca-armory:
    baseService: orca
    image:
      imageId: sha256:595445dfd674c4f13eb88163d46c1a23c907561a3fee9e24df69f31e084c6bbf
      repository: armory/orca-armory
      tag: 2022.04.26.21.43.12.release-2.27.x
    vcs:
      repo:
        orgName: armory-io
        repoName: orca-armory
        type: github
      sha: e18acb93b29b58cf27d15e0cbd2cbff38969938c
  rosco-armory:
    baseService: rosco
    image:
      imageId: sha256:98c9373cc9a1ed27f5a0dcd26212ea607c5f3a32b8a447f85792f96faa4b7dde
      repository: armory/rosco-armory
      tag: 2022.04.27.03.37.44.release-2.27.x
    vcs:
      repo:
        orgName: armory-io
        repoName: rosco-armory
        type: github
      sha: 83405e3fc7725e65619eafdbcbb499a14754fc2b
  terraformer:
    baseService: null
    image:
      imageId: sha256:a76d25ba71acadec6fda2e606c6c98d04b67fa5a104d425e4f44864aacb1c843
      repository: armory/terraformer
      tag: 2022.03.17.09.30.55.release-2.27.x
    vcs:
      repo:
        orgName: armory-io
        repoName: terraformer
        type: github
      sha: 842c8f521bcb715a1569049fa1efed8879baaaec
