services:
  clouddriver-armory:
    baseService: clouddriver
    image:
      imageId: sha256:d9f112ae03175cf5dd95c177fffcb19fec39dabb0c45e215478c107b31fbe102
      repository: armory/clouddriver-armory
      tag: 2023.03.03.02.47.51.release-2.28.x
    vcs:
      repo:
        orgName: armory-io
        repoName: clouddriver-armory
        type: github
      sha: 809dbbab935ebdd5bfa78a9b7259c00d7d1c9d5b
  deck-armory:
    baseService: deck
    image:
      imageId: sha256:acc36e43177beb56bc6ff662b728746397d95189665760fb1dda628a1a424c70
      repository: armory/deck-armory
      tag: 2023.03.08.23.36.52.release-2.28.x
    vcs:
      repo:
        orgName: armory-io
        repoName: deck-armory
        type: github
      sha: c9062f5626855846a1354d274bf1bc7083a86880
  dinghy:
    image:
      imageId: sha256:45ab1532bbb9d48da50951e110e7283ec6a9fc312db6fcb4bd0cc8a7860c35e5
      repository: armory/dinghy
      tag: 2023.03.08.23.37.20.release-2.28.x
    vcs:
      repo:
        orgName: armory-io
        repoName: dinghy
        type: github
      sha: 912007004f7720b418cd133301c7fb20207e1f2f
  echo-armory:
    baseService: echo
    image:
      imageId: sha256:5837c2fad5f0daf8760604d3124e27c038764903cd6d6a6adc8e45e970d5be44
      repository: armory/echo-armory
      tag: 2023.03.02.21.31.31.release-2.28.x
    vcs:
      repo:
        orgName: armory-io
        repoName: echo-armory
        type: github
      sha: 0f80b381e69e958784302fa9506e2f7e17bdcd11
  fiat-armory:
    baseService: fiat
    image:
      imageId: sha256:752c53ef8b2cb6e141935af8e92b31dfb5f2e4b0dde2e52c2a6a5e6febaae5d8
      repository: armory/fiat-armory
      tag: 2023.03.16.18.09.25.release-2.28.x
    vcs:
      repo:
        orgName: armory-io
        repoName: fiat-armory
        type: github
      sha: 45039aa7952cc409329faa30b8443667566459c1
  front50-armory:
    baseService: front50
    image:
      imageId: sha256:f587f52a141ffa3b5dac6688744b4782287b6136839f999181d558d8e846bfa8
      repository: armory/front50-armory
      tag: 2022.12.09.13.31.58.release-2.28.x
    vcs:
      repo:
        orgName: armory-io
        repoName: front50-armory
        type: github
      sha: fab8841982330e7537629c9f24f41205cd5863fd
  gate-armory:
    baseService: gate
    image:
      imageId: sha256:25dcc0d77e07cf828c9ccbef1c96894394fb2c2424e89414bc86fcd04ac0e867
      repository: armory/gate-armory
      tag: 2023.03.02.21.32.13.release-2.28.x
    vcs:
      repo:
        orgName: armory-io
        repoName: gate-armory
        type: github
      sha: a8f59e2ccf13e7cd4072decd2b80eb4542f9e884
  igor-armory:
    baseService: igor
    image:
      imageId: sha256:d7a4d1accf99ef80de1086fb2498759fd8fa463a54d91889e9f8581812a868b8
      repository: armory/igor-armory
      tag: 2023.03.02.21.26.19.release-2.28.x
    vcs:
      repo:
        orgName: armory-io
        repoName: igor-armory
        type: github
      sha: 60964526194a1273a03a7ade1f8939751e337735
  kayenta-armory:
    baseService: kayenta
    image:
      imageId: sha256:821e1915a0af0acddbcb4bcb00747e980148a28f088363f1ba16963973d52a87
      repository: armory/kayenta-armory
      tag: 2023.03.03.05.15.20.release-2.28.x
    vcs:
      repo:
        orgName: armory-io
        repoName: kayenta-armory
        type: github
      sha: 705629b88f6532d4f81dcd8063a31ad55a0ee29b
  orca-armory:
    baseService: orca
    image:
      imageId: sha256:db2454b9cf4b50f095ae56de4b484e8fa84f7d96b4f9e6a25cab088c31a42484
      repository: armory/orca-armory
      tag: 2023.03.02.21.36.38.release-2.28.x
    vcs:
      repo:
        orgName: armory-io
        repoName: orca-armory
        type: github
      sha: 50649da9a4a707f49b180ae50df5ff617ed5e159
  rosco-armory:
    baseService: rosco
    image:
      imageId: sha256:31696ed26cab6ecf5b28890b1cb9a8ae9a517cc0adb04d93bb29b48b97a6195b
      repository: armory/rosco-armory
      tag: 2023.03.02.20.13.03.release-2.28.x
    vcs:
      repo:
        orgName: armory-io
        repoName: rosco-armory
        type: github
      sha: 12b901a2270bba8971c4b44b47e9256db95cd9b4
  terraformer:
    image:
      imageId: sha256:bdc895d272fa3064cf48b00031851e42710c3dd4e865d30f25f69aa8267f746b
      repository: armory/terraformer
      tag: 2023.03.15.01.36.09.release-2.28.x
    vcs:
      repo:
        orgName: armory-io
        repoName: terraformer
        type: github
      sha: ea9b0255b7d446bcbf0f0d4e03fc8699b7508431
