services:
  clouddriver-armory:
    baseService: clouddriver
    image:
      imageId: sha256:5aa87af5e7aba44cd5dba5d4835c6fbd729035851ec08f812f882583acaf1b51
      repository: armory/clouddriver-armory
      tag: 2021.10.01.20.54.09.release-2.26.x
    vcs:
      repo:
        orgName: armory-io
        repoName: clouddriver-armory
        type: github
      sha: 18729608df655fa9ffdf28a968e4bdf22e140e59
  deck-armory:
    baseService: deck
    image:
      imageId: sha256:143946ec5f3fc64140b8ce16d2a70949e9e6dc466d5e1c721625226d17fc06d6
      repository: armory/deck-armory
      tag: 2021.09.23.01.58.49.release-2.26.x
    vcs:
      repo:
        orgName: armory-io
        repoName: deck-armory
        type: github
      sha: 198d62eae2710dceed1f462e50a183abba613fef
  dinghy:
    baseService: null
    image:
      imageId: sha256:9abbb0aca41a1a72613cf4f8c6872ebb22cb4eab929cf1acf6891217ce19360a
      repository: armory/dinghy
      tag: 2021.09.09.19.58.03.release-2.26.x
    vcs:
      repo:
        orgName: armory-io
        repoName: dinghy
        type: github
      sha: d1406fad85771d7f44a266d3302d6195c00d7ec2
  echo-armory:
    baseService: echo
    image:
      imageId: sha256:126a9be2ff81e5ee0d401ebcfbcab00fa6840f56f30a0a061399ff49a992bb35
      repository: armory/echo-armory
      tag: 2021.10.01.18.15.39.release-2.26.x
    vcs:
      repo:
        orgName: armory-io
        repoName: echo-armory
        type: github
      sha: ce4f4ed265be8cb746784c6fd4bed7bf5156107e
  fiat-armory:
    baseService: fiat
    image:
      imageId: sha256:eb0bfe83fac18ed88fa99973db57d833f325959c3ad6f75ee49973a16dd22568
      repository: armory/fiat-armory
      tag: 2021.10.01.21.19.02.release-2.26.x
    vcs:
      repo:
        orgName: armory-io
        repoName: fiat-armory
        type: github
      sha: db5a1bd90f8b1c87d0c0c6eede360a5f50c7ae47
  front50-armory:
    baseService: front50
    image:
      imageId: sha256:91735a57e61e7629231cfc0ef4a847fe061512e7645acd61580ed3401ae26711
      repository: armory/front50-armory
      tag: 2021.10.01.21.33.11.release-2.26.x
    vcs:
      repo:
        orgName: armory-io
        repoName: front50-armory
        type: github
      sha: 7e14c30538a9b97468aba0360408abf4a06bc0dd
  gate-armory:
    baseService: gate
    image:
      imageId: sha256:a93c993ab7dbfaa08b65ba5df9ad8d1fcdc4eb76a592c861978259fd8293f538
      repository: armory/gate-armory
      tag: 2021.10.01.22.56.26.release-2.26.x
    vcs:
      repo:
        orgName: armory-io
        repoName: gate-armory
        type: github
      sha: 99a43759cb8d635d8bd391d9988d47711c6c6f2e
  igor-armory:
    baseService: igor
    image:
      imageId: sha256:c3609288ae9d2d797a5686b64da5686408e7e5f534e3d2d824046b0e61a185a1
      repository: armory/igor-armory
      tag: 2021.10.01.23.09.16.release-2.26.x
    vcs:
      repo:
        orgName: armory-io
        repoName: igor-armory
        type: github
      sha: 889135384533cd723c0a6377a37a7365cf92a8b2
  kayenta-armory:
    baseService: kayenta
    image:
      imageId: sha256:990b49b5034498701fc14c09ab2652f44dd7b75069a4ad7188cfb0af6f083441
      repository: armory/kayenta-armory
      tag: 2021.09.24.21.10.41.release-2.26.x
    vcs:
      repo:
        orgName: armory-io
        repoName: kayenta-armory
        type: github
      sha: 7092324e47c9e0e79e361fa09bfaeecd17e3a9df
  orca-armory:
    baseService: orca
    image:
      imageId: sha256:ff73b951dc036e504d4ec9a14fabc5802673e6cc488ac9760fa178d07566debd
      repository: armory/orca-armory
      tag: 2021.10.01.23.39.04.release-2.26.x
    vcs:
      repo:
        orgName: armory-io
        repoName: orca-armory
        type: github
      sha: 624af61e6bf75bc92e67a6bef6439f8ae29ec79a
  rosco-armory:
    baseService: rosco
    image:
      imageId: sha256:eda88fef11c23d3b55b839197cd1b72ffce214e5ac601e0971ab3ee679a45bc4
      repository: armory/rosco-armory
      tag: 2021.07.01.01.52.23.release-2.26.x
    vcs:
      repo:
        orgName: armory-io
        repoName: rosco-armory
        type: github
      sha: 1dfc60f1f70ccdadc2cc03ff9f27b5ca39bb9c39
  terraformer:
    baseService: null
    image:
      imageId: sha256:eb4e22e641d9dc590f048ba0219c6a2f5ddd9b32bb00efeb74608cffbe0b0d6d
      repository: armory/terraformer
      tag: 2021.09.17.18.01.39.release-2.26.x
    vcs:
      repo:
        orgName: armory-io
        repoName: terraformer
        type: github
      sha: 2dc177734c1445252dfeb3b8353ce94596c8a4c3
