services:
  clouddriver-armory:
    baseService: clouddriver
    image:
      imageId: sha256:d0e829069530c22a069636e4917c4ebde242751f412563b991a96c4736b2d1bf
      repository: armory/clouddriver-armory
      tag: 2022.03.15.22.39.56.release-2.26.x
    vcs:
      repo:
        orgName: armory-io
        repoName: clouddriver-armory
        type: github
      sha: f99488c5a55443f9c39aded2707e2ebec5cd3dff
  deck-armory:
    baseService: deck
    image:
      imageId: sha256:3e69c5ae589de4d937f7d336c27926f2e946348adbd0ae7d54a5ee55b747e9aa
      repository: armory/deck-armory
      tag: 2022.03.17.23.26.12.release-2.26.x
    vcs:
      repo:
        orgName: armory-io
        repoName: deck-armory
        type: github
      sha: 67ad6aba719223720e1a4e8999a85471ba3963a1
  dinghy:
    baseService: null
    image:
      imageId: sha256:298a4b593181ef4dd9428bd646a0f08e54a3ba11db8794381323ddfb7c91c25c
      repository: armory/dinghy
      tag: 2022.01.25.21.40.03.release-2.26.x
    vcs:
      repo:
        orgName: armory-io
        repoName: dinghy
        type: github
      sha: a6248311be12901a4fc8f5a3e0fae437b4347ce3
  echo-armory:
    baseService: echo
    image:
      imageId: sha256:902a59df6b3708c67ba40067ca38bcf5b909d037dad1932f0041f5cd4e4c730d
      repository: armory/echo-armory
      tag: 2022.03.11.01.46.39.release-2.26.x
    vcs:
      repo:
        orgName: armory-io
        repoName: echo-armory
        type: github
      sha: 7da19dfc36ebc5f043d4d69ea1687702761aab18
  fiat-armory:
    baseService: fiat
    image:
      imageId: sha256:c436aea4fc3f150e9fe595752a29aa7a7e04662d58a684af5264783dc89b451b
      repository: armory/fiat-armory
      tag: 2022.03.11.01.46.19.release-2.26.x
    vcs:
      repo:
        orgName: armory-io
        repoName: fiat-armory
        type: github
      sha: 6d812e8b08e557b40b0fb13536725b1c4ed5ec00
  front50-armory:
    baseService: front50
    image:
      imageId: sha256:5edf1845e87a6e65a3fe4e44a3d6f02bca312ade4a12f96d330e37e01e6d1349
      repository: armory/front50-armory
      tag: 2022.03.11.18.27.21.release-2.26.x
    vcs:
      repo:
        orgName: armory-io
        repoName: front50-armory
        type: github
      sha: 086dbc49136fd9805895cc0f5739a9d5a908ab3a
  gate-armory:
    baseService: gate
    image:
      imageId: sha256:c9281caf312c9b4bd5f790fd65aaa5e47a6a852989ac0ece7656270acdca8fb0
      repository: armory/gate-armory
      tag: 2022.03.11.01.47.58.release-2.26.x
    vcs:
      repo:
        orgName: armory-io
        repoName: gate-armory
        type: github
      sha: 76c8cb4d650d506417340e780d2d46869dbf5ae4
  igor-armory:
    baseService: igor
    image:
      imageId: sha256:75ae98087d49bd9d21bc94ba3d341d2a86c9b6d43e2f22f3d8fc7db7eb642887
      repository: armory/igor-armory
      tag: 2022.03.11.01.48.50.release-2.26.x
    vcs:
      repo:
        orgName: armory-io
        repoName: igor-armory
        type: github
      sha: eafa560eaf8c6fce56656dbe0774266ebc96b5b2
  kayenta-armory:
    baseService: kayenta
    image:
      imageId: sha256:ee6be4b5f51d157e092eba84b5094025d82dae2d0e4c44acad8b5ad8616d7f83
      repository: armory/kayenta-armory
      tag: 2022.02.03.22.53.22.release-2.26.x
    vcs:
      repo:
        orgName: armory-io
        repoName: kayenta-armory
        type: github
      sha: 76540e354b3f0784a68d015dc857c25a9a45c76d
  orca-armory:
    baseService: orca
    image:
      imageId: sha256:22b6d773743db167534e50142d66e7aee544103981e7720ca3d6d31a921433db
      repository: armory/orca-armory
      tag: 2022.03.10.20.58.41.release-2.26.x
    vcs:
      repo:
        orgName: armory-io
        repoName: orca-armory
        type: github
      sha: dad21686c41b66c23aa5d3d793b21d52625cb431
  rosco-armory:
    baseService: rosco
    image:
      imageId: sha256:7d77c9186d7b5d60e766e56d04c92b6a41095be1eacf3d9bdd78fd35e6ca9745
      repository: armory/rosco-armory
      tag: 2022.03.17.09.09.50.release-2.26.x
    vcs:
      repo:
        orgName: armory-io
        repoName: rosco-armory
        type: github
      sha: df08490c4e12feae6fb1860ce37a6f3b05cf9834
  terraformer:
    baseService: null
    image:
      imageId: sha256:00654eb77418e5299c3aeeaa78c6fe9b01e7b86731affe96ed73acbe961f1be8
      repository: armory/terraformer
      tag: 2022.03.17.09.32.06.release-2.26.x
    vcs:
      repo:
        orgName: armory-io
        repoName: terraformer
        type: github
      sha: c29b4d7f00c89d4c74953ae465cd2c71cb75ad9a
