services:
  clouddriver-armory:
    baseService: clouddriver
    image:
      imageId: sha256:85d22d87930d064f9591afcd892c61b8971dcc0a9c8c9f484479e925fee74ee2
      repository: armory/clouddriver-armory
      tag: 2021.12.13.18.21.21.release-2.25.x
    vcs:
      repo:
        orgName: armory-io
        repoName: clouddriver-armory
        type: github
      sha: a764fa3dd360655e8ebd9b81e2217fce554f434c
  deck-armory:
    baseService: deck
    image:
      imageId: sha256:0b8eb91b3e7a962116b55c3cff0ae0564ac4ac887062078ed5a00f12b95ee1a8
      repository: armory/deck-armory
      tag: 2021.11.18.23.48.52.release-2.25.x
    vcs:
      repo:
        orgName: armory-io
        repoName: deck-armory
        type: github
      sha: 3be7d16e0ba22113b38a7e8a1862f9769a119d10
  dinghy:
    baseService: null
    image:
      imageId: sha256:a3d442859aa010827463e3a31c1e96799972cec0bf644baf037a95ecb22189c9
      repository: armory/dinghy
      tag: 2021.11.05.15.44.00.release-2.25.x
    vcs:
      repo:
        orgName: armory-io
        repoName: dinghy
        type: github
      sha: 7feba3a7b859b9595758c7c9e09782e651d9f0f8
  echo-armory:
    baseService: echo
    image:
      imageId: sha256:0522a993aa555c7257f17be71a254fb5948be4e5ba93a513b6d0a84e48327f3c
      repository: armory/echo-armory
      tag: 2021.12.13.18.20.11.release-2.25.x
    vcs:
      repo:
        orgName: armory-io
        repoName: echo-armory
        type: github
      sha: d4254bb69d38e8bf9216c045c4380933ff4582e1
  fiat-armory:
    baseService: fiat
    image:
      imageId: sha256:99b7094196aa14253a2b516701950a7295b5385f3a667742109d1b5b109a4fdc
      repository: armory/fiat-armory
      tag: 2021.12.13.18.21.38.release-2.25.x
    vcs:
      repo:
        orgName: armory-io
        repoName: fiat-armory
        type: github
      sha: fe60b6210c6ce00167aa42143a4dffebcf03fb9f
  front50-armory:
    baseService: front50
    image:
      imageId: sha256:9a713416350713da5f01fd29391dfbe6e735393676dcf1adf3a1525978ed3968
      repository: armory/front50-armory
      tag: 2021.12.13.18.21.50.release-2.25.x
    vcs:
      repo:
        orgName: armory-io
        repoName: front50-armory
        type: github
      sha: 3d2302240be46ca85600e488c20059a9990f13d4
  gate-armory:
    baseService: gate
    image:
      imageId: sha256:16e1328082921d104e6821716ae7d6e0ff15678b16861696323654c7b086c10b
      repository: armory/gate-armory
      tag: 2021.12.15.17.12.37.release-2.25.x
    vcs:
      repo:
        orgName: armory-io
        repoName: gate-armory
        type: github
      sha: eab05d036bef8c391274baa7fb3d294862fad37e
  igor-armory:
    baseService: igor
    image:
      imageId: sha256:385991d26039bc303469403dfbceb564494a0605921b6f5e887e610485db150e
      repository: armory/igor-armory
      tag: 2021.12.13.18.22.40.release-2.25.x
    vcs:
      repo:
        orgName: armory-io
        repoName: igor-armory
        type: github
      sha: 670df68838b5183faa5ab42db3559b20bbfb29c9
  kayenta-armory:
    baseService: kayenta
    image:
      imageId: sha256:a96b124169d4e97f8ba115f3c3b8cfbb2bde9b9b1b675ae6e5fdf6fdcffa5eb2
      repository: armory/kayenta-armory
      tag: 2021.12.13.18.28.44.release-2.25.x
    vcs:
      repo:
        orgName: armory-io
        repoName: kayenta-armory
        type: github
      sha: f859543dc93fe2438cca2b7907fde957dde9f64c
  orca-armory:
    baseService: orca
    image:
      imageId: sha256:b1ccb3629b870033e48b7669a46e0186e6b4e954ba5b33f87652bcfbb2e2c087
      repository: armory/orca-armory
      tag: 2021.12.13.18.20.30.release-2.25.x
    vcs:
      repo:
        orgName: armory-io
        repoName: orca-armory
        type: github
      sha: 8f84752ec39945409533737c25beb2a853fa22d0
  rosco-armory:
    baseService: rosco
    image:
      imageId: sha256:6cfbacff42a3f3b8c8095d126143b36cc9dfce3117b477e32b9603a72831b2d3
      repository: armory/rosco-armory
      tag: 2021.12.13.20.37.40.release-2.25.x
    vcs:
      repo:
        orgName: armory-io
        repoName: rosco-armory
        type: github
      sha: 8ef53c816490ac4350813003e098d9ccdff33b0b
  terraformer:
    baseService: null
    image:
      imageId: sha256:d802a0f6b6f1e83001bc0d8d6bc40f170977c0016288dac2d3504cdb8f28dfec
      repository: armory/terraformer
      tag: 2021.11.18.16.12.04.release-2.25.x
    vcs:
      repo:
        orgName: armory-io
        repoName: terraformer
        type: github
      sha: 4551e4c1976da52d1f96033f2849d97dc4c9131c
