services:
  clouddriver-armory:
    baseService: clouddriver
    image:
      imageId: sha256:677a4b7362d6efcd0c6f5dfdc7a6fb60231d3c0e6ac3cf19cd0f5e0869cc19b0
      repository: armory/clouddriver-armory
      tag: 2021.08.04.23.08.40.master
    vcs:
      repo:
        orgName: armory-io
        repoName: clouddriver-armory
        type: github
      sha: b1569b8d43da28e329a928aa379d3da3d2662769
  deck-armory:
    baseService: deck
    image:
      imageId: sha256:12077472e8c2895f0e363ccc8622db2721d33d16e768107f436aec7df4716b9a
      repository: armory/deck-armory
      tag: 2021.08.04.18.04.30.master
    vcs:
      repo:
        orgName: armory-io
        repoName: deck-armory
        type: github
      sha: dc9023cee561f5a3ba23bb5b23687ad422daf56b
  dinghy:
    baseService: null
    image:
      imageId: sha256:981030662d93b8b18f61e4db576d5ee961996be5ed7cc1281fbc84314ee76ff5
      repository: armory/dinghy
      tag: 2021.09.09.20.08.42.master
    vcs:
      repo:
        orgName: armory-io
        repoName: dinghy
        type: github
      sha: 9f3deb2352c26b6355edd085d2e139967338129d
  echo-armory:
    baseService: echo
    image:
      imageId: sha256:40d83e892aa8acf4745523b6eb6d5d234ca77f0b13a3aa3bf3aff23a9d9b4741
      repository: armory/echo-armory
      tag: 2021.09.28.15.35.19.master
    vcs:
      repo:
        orgName: armory-io
        repoName: echo-armory
        type: github
      sha: 720e2188c29b30d50eb614ce1773a5429cbfe70a
  fiat-armory:
    baseService: fiat
    image:
      imageId: sha256:809923d030fd9ee20733001ee54c5226f17a0cecaaae95448726d217e49da403
      repository: armory/fiat-armory
      tag: 2021.10.01.21.01.46.master
    vcs:
      repo:
        orgName: armory-io
        repoName: fiat-armory
        type: github
      sha: 9aa020dc674e0d2900c2fe231d79fa3d546877e2
  front50-armory:
    baseService: front50
    image:
      imageId: sha256:7d92404ffcaeb982f49b621f388c538cac0d60f3396c662b8713921bb12bb7bd
      repository: armory/front50-armory
      tag: 2021.08.04.16.49.32.master
    vcs:
      repo:
        orgName: armory-io
        repoName: front50-armory
        type: github
      sha: 6b8865fb5eab3c0461f18bd2f4b8b31fcb4df6c9
  gate-armory:
    baseService: gate
    image:
      imageId: sha256:a758c54fa14eae1ff36a752d1535294879d816b3b17c51ff07878e823f0f3a72
      repository: armory/gate-armory
      tag: 2021.08.03.21.02.18.master
    vcs:
      repo:
        orgName: armory-io
        repoName: gate-armory
        type: github
      sha: a7adf5d3e3d4dc7aad9d0b680150fdb36f7a21b3
  igor-armory:
    baseService: igor
    image:
      imageId: sha256:0ef5c5c987e12d5dee19df19a648edda0f5006793ffa878dd802eeebbb4d395b
      repository: armory/igor-armory
      tag: 2021.09.28.19.42.36.master
    vcs:
      repo:
        orgName: armory-io
        repoName: igor-armory
        type: github
      sha: ebf9c12a56a4872f07a5b46077ff8ab45c109c02
  kayenta-armory:
    baseService: kayenta
    image:
      imageId: sha256:4fabd59cf91bcb4b4e283184524bf251bb43b6d6bbf350369bc11e02dd145d4d
      repository: armory/kayenta-armory
      tag: 2021.10.01.23.13.04.master
    vcs:
      repo:
        orgName: armory-io
        repoName: kayenta-armory
        type: github
      sha: 2db38c70c660e5214a82e6ab90533b8b69812854
  orca-armory:
    baseService: orca
    image:
      imageId: sha256:e4153f47daf9ed8fc20acc45ba43564cc1e014c4b3a415b7641c5a281c185da0
      repository: armory/orca-armory
      tag: 2021.08.04.23.02.03.master
    vcs:
      repo:
        orgName: armory-io
        repoName: orca-armory
        type: github
      sha: cfe7f10c6a19d4fd63464db69b12ff7cc2d2e210
  rosco-armory:
    baseService: rosco
    image:
      imageId: sha256:e3704da3acc4f9d2f34ef623632086c83d4961ccaca9b88c37a7a9c329ce8746
      repository: armory/rosco-armory
      tag: 2021.10.01.23.37.18.master
    vcs:
      repo:
        orgName: armory-io
        repoName: rosco-armory
        type: github
      sha: 3f16ee2b52559dbfc630365f049bf3b766f0788e
  terraformer:
    baseService: null
    image:
      imageId: sha256:9cc921c8379c9cbd126880b20da7dae62a95579f256652202434e3f4c8edf866
      repository: armory/terraformer
      tag: 2021.09.24.16.00.51.master
    vcs:
      repo:
        orgName: armory-io
        repoName: terraformer
        type: github
      sha: db152dc3998ad2c9bfc3734ddc3fcfdb66705702
