services:
  clouddriver-armory:
    baseService: clouddriver
    image:
      imageId: sha256:f5991fdc34c95de78782106fd24d1ef47338aa86fc27723f1038f1930117508d
      repository: armory/clouddriver-armory
      tag: 2022.03.17.20.14.53.release-2.27.x
    vcs:
      repo:
        orgName: armory-io
        repoName: clouddriver-armory
        type: github
      sha: 438658ac6d1d2cd70923fe76486f2e17234e8825
  deck-armory:
    baseService: deck
    image:
      imageId: sha256:b7078114834b140e5883b4efbbcfd98db72ebb06170101d4c196978400962ceb
      repository: armory/deck-armory
      tag: 2022.03.17.18.45.23.release-2.27.x
    vcs:
      repo:
        orgName: armory-io
        repoName: deck-armory
        type: github
      sha: 6da861c96ef96fa8320889668ad57b600ea53a0b
  dinghy:
    baseService: null
    image:
      imageId: sha256:c24fa4ab0ace8a0728627dd679133a7d1521d98dd5480d9035f860d2dec6452e
      repository: armory/dinghy
      tag: 2022.01.25.21.39.56.release-2.27.x
    vcs:
      repo:
        orgName: armory-io
        repoName: dinghy
        type: github
      sha: ee2e7f8b9778741dae1a5571cb47ac6c76c51d81
  echo-armory:
    baseService: echo
    image:
      imageId: sha256:9c058bb54f5ea57a43f7249901da8c2bd09777d833db48c998fdb17d51871561
      repository: armory/echo-armory
      tag: 2022.03.21.16.08.03.release-2.27.x
    vcs:
      repo:
        orgName: armory-io
        repoName: echo-armory
        type: github
      sha: ff45de5fd8465a9047c04c823de5c8610f5eb4de
  fiat-armory:
    baseService: fiat
    image:
      imageId: sha256:c821f33fc5ce9d70c6a249a3b3566b98a0d7a4349267bbc53b9d3e016089f4a0
      repository: armory/fiat-armory
      tag: 2022.03.17.19.30.05.release-2.27.x
    vcs:
      repo:
        orgName: armory-io
        repoName: fiat-armory
        type: github
      sha: a49b0cc4f842caafa6b78b975cfae02f6a0ac1b0
  front50-armory:
    baseService: front50
    image:
      imageId: sha256:51a4e4b3eb28fd5d58d2d97ebdfe07793abe197b2ffc785461ed490e635d916a
      repository: armory/front50-armory
      tag: 2022.03.04.04.42.14.release-2.27.x
    vcs:
      repo:
        orgName: armory-io
        repoName: front50-armory
        type: github
      sha: cdb90f4dc3d55c2a5150a3e573b1862cef93816b
  gate-armory:
    baseService: gate
    image:
      imageId: sha256:a987d3e66fe80f6f3fcf02e6874928e1ffe8e92383be3c7f56ee172efa4f81e1
      repository: armory/gate-armory
      tag: 2022.03.17.19.31.32.release-2.27.x
    vcs:
      repo:
        orgName: armory-io
        repoName: gate-armory
        type: github
      sha: 9895b83d6f5856a039233c77586582c791db4876
  igor-armory:
    baseService: igor
    image:
      imageId: sha256:ccf41cc09ff57b0bdc76fb31b407d7e9d613658dde2c7b16849b13e24e4adfd4
      repository: armory/igor-armory
      tag: 2022.03.17.19.29.59.release-2.27.x
    vcs:
      repo:
        orgName: armory-io
        repoName: igor-armory
        type: github
      sha: f11df55a9398f4efbc641e85afde34fdccbed3a2
  kayenta-armory:
    baseService: kayenta
    image:
      imageId: sha256:f43330f30abcf97d06c4ff29ac13dad76800d1682cb4b1ff1d8bd62f85f2f909
      repository: armory/kayenta-armory
      tag: 2022.02.22.23.20.32.release-2.27.x
    vcs:
      repo:
        orgName: armory-io
        repoName: kayenta-armory
        type: github
      sha: 800b14c9162cc0f486f4e7f510f87ec8db9b5e98
  orca-armory:
    baseService: orca
    image:
      imageId: sha256:5a08f0fe22d035f7252f6b2a32c23068993257a566ad04ae862e168976f4502f
      repository: armory/orca-armory
      tag: 2022.03.17.19.35.13.release-2.27.x
    vcs:
      repo:
        orgName: armory-io
        repoName: orca-armory
        type: github
      sha: 29564d884403dbedbefffba9d8523a2ced4983ac
  rosco-armory:
    baseService: rosco
    image:
      imageId: sha256:f17cd7f319b8c0a421e2a5e4ebe06e17b8c8e3ca9c46564fbfc32169009d8147
      repository: armory/rosco-armory
      tag: 2022.03.21.18.58.32.release-2.27.x
    vcs:
      repo:
        orgName: armory-io
        repoName: rosco-armory
        type: github
      sha: 13033521bd3209b2879e56af4710f6ea32816a90
  terraformer:
    baseService: null
    image:
      imageId: sha256:a76d25ba71acadec6fda2e606c6c98d04b67fa5a104d425e4f44864aacb1c843
      repository: armory/terraformer
      tag: 2022.03.17.09.30.55.release-2.27.x
    vcs:
      repo:
        orgName: armory-io
        repoName: terraformer
        type: github
      sha: 842c8f521bcb715a1569049fa1efed8879baaaec
