services:
  orca-armory:
    baseService: orca
    image:
      imageId: sha256:2bd85d398d7915788af703ab186b62f6d22613b097bd06c8003582bda9c1a403
      repository: armory/orca-armory
      tag: 2021.05.13.19.36.47.master
    vcs:
      repo:
        orgName: armory-io
        repoName: orca-armory
        type: github
      sha: 0b588c58836654dc532b100183591df8c34b0494
