services:
  clouddriver-armory:
    baseService: clouddriver
    image:
      imageId: sha256:57cf00ab2b29bc9547467a2e62caf16fa2be0f48ae914ca3fe2432a3b292eddf
      repository: armory/clouddriver-armory
      tag: 2022.07.06.00.14.57.release-2.28.x
    vcs:
      repo:
        orgName: armory-io
        repoName: clouddriver-armory
        type: github
      sha: 4bdd7850e874672bdc1f8cc360c08b7e9497b4ff
  deck-armory:
    baseService: deck
    image:
      imageId: sha256:020777d72afd3240c7b01e71ae1c9202742ffb38c83d1f14402c731ea3527965
      repository: armory/deck-armory
      tag: 2022.07.07.00.07.26.release-2.28.x
    vcs:
      repo:
        orgName: armory-io
        repoName: deck-armory
        type: github
      sha: cba7fd84457fd2dc97fe10ac62acd6c467a88031
  dinghy:
    baseService: null
    image:
      imageId: sha256:468ccfb9d9e6f60b2d4aa21ef9b93bb73e3f0c1a0940c04a479b794e46ecdc97
      repository: armory/dinghy
      tag: 2022.01.25.21.22.55.release-2.28.x
    vcs:
      repo:
        orgName: armory-io
        repoName: dinghy
        type: github
      sha: 403640bc88ad42cc55105bff773408d5f845e49c
  echo-armory:
    baseService: echo
    image:
      imageId: sha256:002527a18af4db4ab0f69537d4825024fbf494afafb9a541ffd62a784232d744
      repository: armory/echo-armory
      tag: 2022.05.20.19.48.50.release-2.28.x
    vcs:
      repo:
        orgName: armory-io
        repoName: echo-armory
        type: github
      sha: 488477dd85edfc6206337bb31f76892e641d1803
  fiat-armory:
    baseService: fiat
    image:
      imageId: sha256:504cc065491151d15eafadeb4ef9de748065ce5d4f134c54648b64b354faa736
      repository: armory/fiat-armory
      tag: 2022.05.20.23.15.25.release-2.28.x
    vcs:
      repo:
        orgName: armory-io
        repoName: fiat-armory
        type: github
      sha: 9aca7990e68cc8022a55af31db7df1d04e02de4c
  front50-armory:
    baseService: front50
    image:
      imageId: sha256:8b52343aa203dff789caef5ae8236012a762c46636899a8f072c71015e167cc7
      repository: armory/front50-armory
      tag: 2022.06.24.22.45.18.release-2.28.x
    vcs:
      repo:
        orgName: armory-io
        repoName: front50-armory
        type: github
      sha: ce9e9eea6aad61957643fd6ced6b52102773a90a
  gate-armory:
    baseService: gate
    image:
      imageId: sha256:685098d5310198c6037461f65d4c665902bfc8e42aa81d82213e2bbed934d151
      repository: armory/gate-armory
      tag: 2022.07.01.23.28.17.release-2.28.x
    vcs:
      repo:
        orgName: armory-io
        repoName: gate-armory
        type: github
      sha: 938dccc232f849bae4446376579a39755267904b
  igor-armory:
    baseService: igor
    image:
      imageId: sha256:9a31a3dfd2558416a41cb0959240f53c1e0b150ee125713613e004157fd97457
      repository: armory/igor-armory
      tag: 2022.05.18.20.57.02.release-2.28.x
    vcs:
      repo:
        orgName: armory-io
        repoName: igor-armory
        type: github
      sha: 5ea6da54f840ecaffa72d62386d9efd7bb54e0fe
  kayenta-armory:
    baseService: kayenta
    image:
      imageId: sha256:7f9d667e7a353e6406442fdbc6392eebeeb46aa2ee0a8b63f6300810191221e0
      repository: armory/kayenta-armory
      tag: 2022.05.18.21.13.15.release-2.28.x
    vcs:
      repo:
        orgName: armory-io
        repoName: kayenta-armory
        type: github
      sha: ebc7a92d06ed18b93233a6c887fe9acfd85ccc8c
  orca-armory:
    baseService: orca
    image:
      imageId: sha256:2b83a64577896371246ce68c97323c8c3f632b4bda0f66112383bc11c8b86acb
      repository: armory/orca-armory
      tag: 2022.05.18.20.57.13.release-2.28.x
    vcs:
      repo:
        orgName: armory-io
        repoName: orca-armory
        type: github
      sha: 877733807a0661adef388e9ad45f79506428e2fe
  rosco-armory:
    baseService: rosco
    image:
      imageId: sha256:c1c5df9e9d42148cf1c783d74ed5ae8c2a48ac98be043e7e21388d72b7e58234
      repository: armory/rosco-armory
      tag: 2022.05.20.19.37.45.release-2.28.x
    vcs:
      repo:
        orgName: armory-io
        repoName: rosco-armory
        type: github
      sha: 8878e069687bfd229bd00907ede66dfe1b73d2e0
  terraformer:
    baseService: null
    image:
      imageId: sha256:27e5c5a4fa7e8d0e7595dd2a157578ef97f535c826d767033fa44f99ef29878d
      repository: armory/terraformer
      tag: 2022.06.08.17.56.10.release-2.28.x
    vcs:
      repo:
        orgName: armory-io
        repoName: terraformer
        type: github
      sha: c3c07a7c4f09752409183f906fb9fa5458e7d602
