services:
  clouddriver-armory:
    baseService: clouddriver
    image:
      imageId: sha256:6f6d0d6cf14a2e3b917178a35b50a911347ad272ee460c003065be7f09b8720a
      repository: armory/clouddriver-armory
      tag: 2021.10.26.20.31.38.release-2.27.x
    vcs:
      repo:
        orgName: armory-io
        repoName: clouddriver-armory
        type: github
      sha: 7ebce68b12380aef189fa5fd4e8d2b3f7dada086
  deck-armory:
    baseService: deck
    image:
      imageId: sha256:bc896c20b60953ef335168210b99b694aded5a7c1d879c92fb77d64b3c587f3e
      repository: armory/deck-armory
      tag: 2021.09.28.19.21.51.release-2.27.x
    vcs:
      repo:
        orgName: armory-io
        repoName: deck-armory
        type: github
      sha: 8912ef4f4a4f171384497b787aee0e83847ffd5c
  dinghy:
    baseService: null
    image:
      imageId: sha256:3d7040558f76025a9235de3a01a9ff1bf98abd3884826cc94f3e24d8a2b6b631
      repository: armory/dinghy
      tag: 2021.09.09.19.58.08.release-2.27.x
    vcs:
      repo:
        orgName: armory-io
        repoName: dinghy
        type: github
      sha: 71f2ed003fe6b75d8e4f43e800725f2ff3a8a1fe
  echo-armory:
    baseService: echo
    image:
      imageId: sha256:e0170108500db0d1813749d2a038e91304103a1eaf33c41af3707e2b83244c61
      repository: armory/echo-armory
      tag: 2021.09.28.18.25.53.release-2.27.x
    vcs:
      repo:
        orgName: armory-io
        repoName: echo-armory
        type: github
      sha: 5ec4a67ff921c2bdefc776dda03a0780ff853bcf
  fiat-armory:
    baseService: fiat
    image:
      imageId: sha256:d8d891e50a050f39af18c8b98b89ec67e93441d0422bfb3a06899c6ae5e4b716
      repository: armory/fiat-armory
      tag: 2021.10.26.20.11.47.release-2.27.x
    vcs:
      repo:
        orgName: armory-io
        repoName: fiat-armory
        type: github
      sha: f23a1b97346816afc4e8e85dfc3ac137282af64a
  front50-armory:
    baseService: front50
    image:
      imageId: sha256:d9ec005a187c956831fcc131dc8fa738612cbe41fbe6b23f8b2a96924bda1608
      repository: armory/front50-armory
      tag: 2021.10.28.01.53.02.release-2.27.x
    vcs:
      repo:
        orgName: armory-io
        repoName: front50-armory
        type: github
      sha: f6339ea78bf6edc39250289b1a9e5545d53bc94f
  gate-armory:
    baseService: gate
    image:
      imageId: sha256:d693a4c923791e28a0a0d77077c8acf3843c41a2187e4b977e0fd3d6f1db9657
      repository: armory/gate-armory
      tag: 2021.10.01.21.47.32.release-2.27.x
    vcs:
      repo:
        orgName: armory-io
        repoName: gate-armory
        type: github
      sha: 2de972d861f5c8a276e332082530b4cb3d65b576
  igor-armory:
    baseService: igor
    image:
      imageId: sha256:3e777e695fa5a618b85641a99c1c774f56d9c56d9fd17684845ec3ed95e3fa94
      repository: armory/igor-armory
      tag: 2021.09.28.19.51.59.release-2.27.x
    vcs:
      repo:
        orgName: armory-io
        repoName: igor-armory
        type: github
      sha: 9f4db42f060f6fb45aad4c038525d71528a2f9f5
  kayenta-armory:
    baseService: kayenta
    image:
      imageId: sha256:560cf69466f1ad2c41a9fde7c14e6fdea7358c1cb16903fa04bb1401bbf8d355
      repository: armory/kayenta-armory
      tag: 2021.10.01.23.35.47.release-2.27.x
    vcs:
      repo:
        orgName: armory-io
        repoName: kayenta-armory
        type: github
      sha: 1cdf69a42c359a1f12077b6b1cba5606ac3e5daf
  orca-armory:
    baseService: orca
    image:
      imageId: sha256:911dd2d56baf43484bd28ee84b1efdf14708771d55be383e86c6fbcda7650694
      repository: armory/orca-armory
      tag: 2021.10.26.20.11.53.release-2.27.x
    vcs:
      repo:
        orgName: armory-io
        repoName: orca-armory
        type: github
      sha: 522655a252c5a1a97f7745fe622ba06bccb99a8c
  rosco-armory:
    baseService: rosco
    image:
      imageId: sha256:2bc2ee1709e70fb8d93cfff77ebdd838509d7c5843a8c48e9e7dd288bfca95df
      repository: armory/rosco-armory
      tag: 2021.10.01.23.48.56.release-2.27.x
    vcs:
      repo:
        orgName: armory-io
        repoName: rosco-armory
        type: github
      sha: ac6fe57054e435c6058911c4caa177cba5fa64b3
  terraformer:
    baseService: null
    image:
      imageId: sha256:efc94a46946188ca16226916ad8e289c85ac03bd5e54c6144dc9c4ba1b68c148
      repository: armory/terraformer
      tag: 2021.10.27.15.43.06.release-2.27.x
    vcs:
      repo:
        orgName: armory-io
        repoName: terraformer
        type: github
      sha: 5e69c32279c6516047eaf6de261d3632095677aa
