services:
  clouddriver-armory:
    baseService: clouddriver
    image:
      imageId: sha256:d686c4c73e4f3eb9d60acd0f3470c7fc9dbba631832b9dd723f0e378c1bb4be7
      repository: armory/clouddriver-armory
      tag: 2022.04.02.00.10.25.release-2.27.x
    vcs:
      repo:
        orgName: armory-io
        repoName: clouddriver-armory
        type: github
      sha: 283908aac8d67edc6942cd12c59709add4a076a6
  deck-armory:
    baseService: deck
    image:
      imageId: sha256:3eb83c0a9b05b515ab291c635d117b812530d3e68854ec72b62ca78a1eb73d58
      repository: armory/deck-armory
      tag: 2022.03.23.23.24.53.release-2.27.x
    vcs:
      repo:
        orgName: armory-io
        repoName: deck-armory
        type: github
      sha: e1207937e2987406ba6d9f07b9c1bf683f57e3da
  dinghy:
    baseService: null
    image:
      imageId: sha256:c24fa4ab0ace8a0728627dd679133a7d1521d98dd5480d9035f860d2dec6452e
      repository: armory/dinghy
      tag: 2022.01.25.21.39.56.release-2.27.x
    vcs:
      repo:
        orgName: armory-io
        repoName: dinghy
        type: github
      sha: ee2e7f8b9778741dae1a5571cb47ac6c76c51d81
  echo-armory:
    baseService: echo
    image:
      imageId: sha256:672cddd114158bb0d5f9cead0c4f86cffa44a4f7a62a805bf3365bffbd8f1395
      repository: armory/echo-armory
      tag: 2022.04.01.23.52.59.release-2.27.x
    vcs:
      repo:
        orgName: armory-io
        repoName: echo-armory
        type: github
      sha: 04ca6ca6f66a466fb4e66f8bf23f12135e3de4a2
  fiat-armory:
    baseService: fiat
    image:
      imageId: sha256:89eba3716c1b9bee5d4ffa54255f14992a02f88c758a2ca7a8ad9926172e8a1b
      repository: armory/fiat-armory
      tag: 2022.04.01.22.56.49.release-2.27.x
    vcs:
      repo:
        orgName: armory-io
        repoName: fiat-armory
        type: github
      sha: e26b2c10bccf5a82473482efda2fc710430b803a
  front50-armory:
    baseService: front50
    image:
      imageId: sha256:94a126a666318fa68dbc2d7edc6266b32e74c116e7f802e873fbc7e5f78cfedb
      repository: armory/front50-armory
      tag: 2022.04.01.23.28.57.release-2.27.x
    vcs:
      repo:
        orgName: armory-io
        repoName: front50-armory
        type: github
      sha: ea9bb4a7c20fd81050e4fe38e3ed708de66d3f7f
  gate-armory:
    baseService: gate
    image:
      imageId: sha256:0a40182b5d5717115db02d1541f411ca8215c08415a013a7d9484019246d77b4
      repository: armory/gate-armory
      tag: 2022.04.02.00.09.14.release-2.27.x
    vcs:
      repo:
        orgName: armory-io
        repoName: gate-armory
        type: github
      sha: 006ed54db3f9ea3b775cd955ecd60503a748fb2c
  igor-armory:
    baseService: igor
    image:
      imageId: sha256:0ab05599fe167b8e1f0fc4188c002b04a986ed6802ecc7fe035454dbdefffc8a
      repository: armory/igor-armory
      tag: 2022.04.02.03.10.37.release-2.27.x
    vcs:
      repo:
        orgName: armory-io
        repoName: igor-armory
        type: github
      sha: 94c9f9ff6fa163fae8967ee51a36e01c3cd306d4
  kayenta-armory:
    baseService: kayenta
    image:
      imageId: sha256:f43330f30abcf97d06c4ff29ac13dad76800d1682cb4b1ff1d8bd62f85f2f909
      repository: armory/kayenta-armory
      tag: 2022.02.22.23.20.32.release-2.27.x
    vcs:
      repo:
        orgName: armory-io
        repoName: kayenta-armory
        type: github
      sha: 800b14c9162cc0f486f4e7f510f87ec8db9b5e98
  orca-armory:
    baseService: orca
    image:
      imageId: sha256:fa28a1671349daf546d1a00495e71528d2141516d03101df72b2c9fd0f2ca803
      repository: armory/orca-armory
      tag: 2022.04.02.02.55.47.release-2.27.x
    vcs:
      repo:
        orgName: armory-io
        repoName: orca-armory
        type: github
      sha: 015174b95930462dff99f799f90f1845bc36b60d
  rosco-armory:
    baseService: rosco
    image:
      imageId: sha256:aaa6489d8b8b9c7452566441621439078e9566e93ae2b2f7de9e9bc6c30d85d1
      repository: armory/rosco-armory
      tag: 2022.04.01.23.45.10.release-2.27.x
    vcs:
      repo:
        orgName: armory-io
        repoName: rosco-armory
        type: github
      sha: 5d9d7a4776230a2b2b3571ded6086f33644a209b
  terraformer:
    baseService: null
    image:
      imageId: sha256:a76d25ba71acadec6fda2e606c6c98d04b67fa5a104d425e4f44864aacb1c843
      repository: armory/terraformer
      tag: 2022.03.17.09.30.55.release-2.27.x
    vcs:
      repo:
        orgName: armory-io
        repoName: terraformer
        type: github
      sha: 842c8f521bcb715a1569049fa1efed8879baaaec
