services:
  clouddriver-armory:
    baseService: clouddriver
    image:
      imageId: sha256:221fdb9eded6763a2ebab10555c2274d83450df7306454f7c1a261cb7cfc9086
      repository: armory/clouddriver-armory
      tag: 2023.06.15.08.45.13.release-2.30.x
    vcs:
      repo:
        orgName: armory-io
        repoName: clouddriver-armory
        type: github
      sha: 4512ba1b391b06d49a017b29113010631ddabb14
  deck-armory:
    baseService: deck
    image:
      imageId: sha256:61a1f24bc465553aff2614cfb81cf0e6f1d8e9bce7a3a17cb5edc70b2381b475
      repository: armory/deck-armory
      tag: 2023.04.15.02.46.39.release-2.30.x
    vcs:
      repo:
        orgName: armory-io
        repoName: deck-armory
        type: github
      sha: a5ae63596f79df5c3dd4999253a9ed72dece7de3
  dinghy:
    image:
      imageId: sha256:0c5ac601aabb6bced977c27355b40bdfde0f39b870b131db919190d2cc590066
      repository: armory/dinghy
      tag: 2023.03.08.19.45.23.release-2.30.x
    vcs:
      repo:
        orgName: armory-io
        repoName: dinghy
        type: github
      sha: 5250de80948732c8caac6ffc5293a8af80a63a0f
  echo-armory:
    baseService: echo
    image:
      imageId: sha256:a1807d84952dcc610ed32c061a932f3734708ede8a68bc63d500675e6c51071b
      repository: armory/echo-armory
      tag: 2023.05.12.15.22.43.release-2.30.x
    vcs:
      repo:
        orgName: armory-io
        repoName: echo-armory
        type: github
      sha: 86c586f7c523a4c320189eff00731271b8d31e32
  fiat-armory:
    baseService: fiat
    image:
      imageId: sha256:2792b1ebe09cf7d1e943f2c08d6fd2ba8c8d506ecc4e07acbec1276e5a94bc93
      repository: armory/fiat-armory
      tag: 2023.05.12.15.23.21.release-2.30.x
    vcs:
      repo:
        orgName: armory-io
        repoName: fiat-armory
        type: github
      sha: 0150c145b239568c294ab88251dc2fbb20ace279
  front50-armory:
    baseService: front50
    image:
      imageId: sha256:5afe911bf2f854f7a5faa7e1045b72433104729e8e72b0b60e09a31ac807556b
      repository: armory/front50-armory
      tag: 2023.05.23.15.48.49.release-2.30.x
    vcs:
      repo:
        orgName: armory-io
        repoName: front50-armory
        type: github
      sha: bdbf36960c30b3599bdf0fa31620dfaf08927074
  gate-armory:
    baseService: gate
    image:
      imageId: sha256:a223e589da67f33a4059eaa8908f312e411a1c5a918150ef0e94f23ad9de983b
      repository: armory/gate-armory
      tag: 2023.05.12.15.24.13.release-2.30.x
    vcs:
      repo:
        orgName: armory-io
        repoName: gate-armory
        type: github
      sha: 679225a36b20fe39ecb175813929972c497d1a92
  igor-armory:
    baseService: igor
    image:
      imageId: sha256:a0d5aab8e48affd69a374b686aa761a9db71972398b6344be1b76ab42d71bd47
      repository: armory/igor-armory
      tag: 2023.05.12.15.23.43.release-2.30.x
    vcs:
      repo:
        orgName: armory-io
        repoName: igor-armory
        type: github
      sha: 020e01bbeaadf3d5eb745b33180bd1011c4b068f
  kayenta-armory:
    baseService: kayenta
    image:
      imageId: sha256:2ad90b5f29d1eed73a840bec39ce5b631ac6e3489728e793acb2770afee35e4f
      repository: armory/kayenta-armory
      tag: 2023.05.12.15.39.01.release-2.30.x
    vcs:
      repo:
        orgName: armory-io
        repoName: kayenta-armory
        type: github
      sha: 16aa401c453de95b670524b491cbaa682bcf2817
  orca-armory:
    baseService: orca
    image:
      imageId: sha256:269ad5e4232f8739e05a474b3f42533965b1d27f034958f86bf9de307cfdce0a
      repository: armory/orca-armory
      tag: 2023.05.18.14.39.29.release-2.30.x
    vcs:
      repo:
        orgName: armory-io
        repoName: orca-armory
        type: github
      sha: 25ccf32473a809846c1c3d4c967bb05ad9622549
  rosco-armory:
    baseService: rosco
    image:
      imageId: sha256:5642a04c46c45dfc3b115ef751429c8a82c606859d95fde44b809af2e4ccce03
      repository: armory/rosco-armory
      tag: 2023.05.12.15.27.29.release-2.30.x
    vcs:
      repo:
        orgName: armory-io
        repoName: rosco-armory
        type: github
      sha: c72a24d8c560ea7b27fd8ecf45c9c11ca63682f4
  terraformer:
    image:
      imageId: sha256:f7529582852992f1144118c0da7d099b1cb3c13c587e0dd065480769b7ca2184
      repository: armory/terraformer
      tag: 2023.01.05.16.17.47.release-2.30.x
    vcs:
      repo:
        orgName: armory-io
        repoName: terraformer
        type: github
      sha: 418546f57129380e383e62b6178ed582e6d64a93
