services:
  clouddriver-armory:
    baseService: clouddriver
    image:
      imageId: sha256:3b4e58b26c57cf31e72b5435dfcffea6e7daeb856c501042f39c460cc1359334
      repository: armory/clouddriver-armory
      tag: 2022.11.29.23.12.07.release-2.28.x
    vcs:
      repo:
        orgName: armory-io
        repoName: clouddriver-armory
        type: github
      sha: 960c72d1e7e7b9e857d94af9731c3441426ee073
  deck-armory:
    baseService: deck
    image:
      imageId: sha256:d0ed20728b1fd4d6e39251b678e1f1203e997aec62225342089655f1df7d7238
      repository: armory/deck-armory
      tag: 2022.11.08.20.41.07.release-2.28.x
    vcs:
      repo:
        orgName: armory-io
        repoName: deck-armory
        type: github
      sha: bd4fb67ec81c5e201b31b4e3e7829dff93476580
  dinghy:
    image:
      imageId: sha256:b5f35d09884647a6b8ff9ac6e4bc34ce27def1af573f20786ff252531768a24d
      repository: armory/dinghy
      tag: 2022.10.22.00.16.44.release-2.28.x
    vcs:
      repo:
        orgName: armory-io
        repoName: dinghy
        type: github
      sha: fc867f05b41e5e2756c42990b576341973e96276
  echo-armory:
    baseService: echo
    image:
      imageId: sha256:5579ea9c2b2f59673027fef48ea495550f2b3b5cf7aa8389dffa4c601f6343bd
      repository: armory/echo-armory
      tag: 2022.10.19.20.14.04.release-2.28.x
    vcs:
      repo:
        orgName: armory-io
        repoName: echo-armory
        type: github
      sha: 010bdc55d57c1000ef93f826204e6ccf54f6f6e7
  fiat-armory:
    baseService: fiat
    image:
      imageId: sha256:ca964c0cc66202710004093fbbe1f7ba57397df224f0b620e5e99548d46239b6
      repository: armory/fiat-armory
      tag: 2022.08.03.03.22.19.release-2.28.x
    vcs:
      repo:
        orgName: armory-io
        repoName: fiat-armory
        type: github
      sha: fce52482097b606389328d25d220be5eaaddab21
  front50-armory:
    baseService: front50
    image:
      imageId: sha256:615e30d68e610d39e9142ad242ae997b4d7aa18f284301b128c52394ec481081
      repository: armory/front50-armory
      tag: 2022.09.12.22.49.17.release-2.28.x
    vcs:
      repo:
        orgName: armory-io
        repoName: front50-armory
        type: github
      sha: 1e5d3a5dfce38d26f809dee107d8145c00caa27e
  gate-armory:
    baseService: gate
    image:
      imageId: sha256:f8e03bbacca701c8bf297c5d0ba47cfb181fca05bd92055d9a3fb52ac10fef6e
      repository: armory/gate-armory
      tag: 2022.12.01.03.50.54.release-2.28.x
    vcs:
      repo:
        orgName: armory-io
        repoName: gate-armory
        type: github
      sha: 65bdd30238312bbca2dce613825eda7ae88f1dfa
  igor-armory:
    baseService: igor
    image:
      imageId: sha256:51aa1f04074378b46714e3103f3df21fd95624879f76793be78b3dc33e354d93
      repository: armory/igor-armory
      tag: 2022.11.29.22.25.00.release-2.28.x
    vcs:
      repo:
        orgName: armory-io
        repoName: igor-armory
        type: github
      sha: 61ce26babfcd0bdf62872c24e707ca5b5371a381
  kayenta-armory:
    baseService: kayenta
    image:
      imageId: sha256:9838378f1c74ba0701dfab201031e48ff465b558d04b2f0bd05b73d6f500418c
      repository: armory/kayenta-armory
      tag: 2022.08.19.04.54.33.release-2.28.x
    vcs:
      repo:
        orgName: armory-io
        repoName: kayenta-armory
        type: github
      sha: 6004bfd90ad2e4fa9b02dddc26253210b8aa3a3c
  orca-armory:
    baseService: orca
    image:
      imageId: sha256:bead16ac9781a8fff3306abf865818f39afeadcedbc0f2bd9f49c899d1ddaf17
      repository: armory/orca-armory
      tag: 2022.11.21.16.47.31.release-2.28.x
    vcs:
      repo:
        orgName: armory-io
        repoName: orca-armory
        type: github
      sha: 81226e48744c3ab5ce1afe68e20ae4aa8e6487dd
  rosco-armory:
    baseService: rosco
    image:
      imageId: sha256:b72f595dc6010490fa7e2ccfac9cdde0ece360747951d0cca8701f8dbb72437c
      repository: armory/rosco-armory
      tag: 2022.11.29.22.28.54.release-2.28.x
    vcs:
      repo:
        orgName: armory-io
        repoName: rosco-armory
        type: github
      sha: 33e7e7db7e2475f0a5ce8c42f7ccc986d8c134fa
  terraformer:
    image:
      imageId: sha256:e1a7e1edb8b3aa564c9abb0f042ca10d4344b157e297f863149fa04a7891e986
      repository: armory/terraformer
      tag: 2022.11.16.18.59.47.release-2.28.x
    vcs:
      repo:
        orgName: armory-io
        repoName: terraformer
        type: github
      sha: 6b721988b67473db3e4d9267432c609b5176274d
