services:
  clouddriver-armory:
    baseService: clouddriver
    image:
      imageId: sha256:3b4e58b26c57cf31e72b5435dfcffea6e7daeb856c501042f39c460cc1359334
      repository: armory/clouddriver-armory
      tag: 2022.11.29.23.12.07.release-2.28.x
    vcs:
      repo:
        orgName: armory-io
        repoName: clouddriver-armory
        type: github
      sha: 960c72d1e7e7b9e857d94af9731c3441426ee073
  deck-armory:
    baseService: deck
    image:
      imageId: sha256:831b5991014a71528336fe158a78a12c48f32bd9bd97eb9c704354a3aa892ff0
      repository: armory/deck-armory
      tag: 2022.12.15.10.19.52.release-2.28.x
    vcs:
      repo:
        orgName: armory-io
        repoName: deck-armory
        type: github
      sha: dd17c153eaf117ab7990c11182a6bdc887d020f9
  dinghy:
    image:
      imageId: sha256:a8f210423b9b1ceec1827fc184c9b298fbdb55fcd5f6f841bb1a354c71c5c1cd
      repository: armory/dinghy
      tag: 2022.12.08.13.48.09.release-2.28.x
    vcs:
      repo:
        orgName: armory-io
        repoName: dinghy
        type: github
      sha: c4ed5b19dbcfefe8dea14cdff7df9a8ab540eba3
  echo-armory:
    baseService: echo
    image:
      imageId: sha256:d68d89642440483b824ae20361e1095a13245112c52cfc0e260d073449c6e0c3
      repository: armory/echo-armory
      tag: 2022.12.06.20.33.41.release-2.28.x
    vcs:
      repo:
        orgName: armory-io
        repoName: echo-armory
        type: github
      sha: 6d4e4ae054b7a13050a1d271b3c771a790e27fc6
  fiat-armory:
    baseService: fiat
    image:
      imageId: sha256:4bdd475a9aa16b2d2682b3ddc78b990e79598d101be326d044ecba46701b0c16
      repository: armory/fiat-armory
      tag: 2022.12.13.21.00.40.release-2.28.x
    vcs:
      repo:
        orgName: armory-io
        repoName: fiat-armory
        type: github
      sha: 48c8759b0878fd1b86b91dae9ee288afcf03dd39
  front50-armory:
    baseService: front50
    image:
      imageId: sha256:f587f52a141ffa3b5dac6688744b4782287b6136839f999181d558d8e846bfa8
      repository: armory/front50-armory
      tag: 2022.12.09.13.31.58.release-2.28.x
    vcs:
      repo:
        orgName: armory-io
        repoName: front50-armory
        type: github
      sha: fab8841982330e7537629c9f24f41205cd5863fd
  gate-armory:
    baseService: gate
    image:
      imageId: sha256:f8e03bbacca701c8bf297c5d0ba47cfb181fca05bd92055d9a3fb52ac10fef6e
      repository: armory/gate-armory
      tag: 2022.12.01.03.50.54.release-2.28.x
    vcs:
      repo:
        orgName: armory-io
        repoName: gate-armory
        type: github
      sha: 65bdd30238312bbca2dce613825eda7ae88f1dfa
  igor-armory:
    baseService: igor
    image:
      imageId: sha256:51aa1f04074378b46714e3103f3df21fd95624879f76793be78b3dc33e354d93
      repository: armory/igor-armory
      tag: 2022.11.29.22.25.00.release-2.28.x
    vcs:
      repo:
        orgName: armory-io
        repoName: igor-armory
        type: github
      sha: 61ce26babfcd0bdf62872c24e707ca5b5371a381
  kayenta-armory:
    baseService: kayenta
    image:
      imageId: sha256:af024d71f2edb7cc8543bf6657faffee660a02eb3e574804b54acde8bd9cc6b6
      repository: armory/kayenta-armory
      tag: 2022.12.16.05.57.53.release-2.28.x
    vcs:
      repo:
        orgName: armory-io
        repoName: kayenta-armory
        type: github
      sha: 0333b9ed6153acfc090edcfa38e3514439e2863c
  orca-armory:
    baseService: orca
    image:
      imageId: sha256:095e67052dd638394036284875be872757e7fa46031269d701ed9f963ec22c29
      repository: armory/orca-armory
      tag: 2022.11.27.20.26.41.release-2.28.x
    vcs:
      repo:
        orgName: armory-io
        repoName: orca-armory
        type: github
      sha: 76fe72a46566bb404eb4db4c842ecb0775c546bf
  rosco-armory:
    baseService: rosco
    image:
      imageId: sha256:6506612f316494a25f4c408fdd28c06b8ea1d0eca0abf2e7c2835a4e6f8f1500
      repository: armory/rosco-armory
      tag: 2022.12.08.22.01.17.release-2.28.x
    vcs:
      repo:
        orgName: armory-io
        repoName: rosco-armory
        type: github
      sha: 945f21dec252da7dd2e00c8d23a1687aa3b9841a
  terraformer:
    image:
      imageId: sha256:9d425ad59a69f3f303005661d1ec783631a0fc4c68c5db8402ad9af1b743b16b
      repository: armory/terraformer
      tag: 2022.12.14.20.52.44.release-2.28.x
    vcs:
      repo:
        orgName: armory-io
        repoName: terraformer
        type: github
      sha: 0d18998cb4790dd4857d79e318d873450bd5975d
