services:
  clouddriver-armory:
    baseService: clouddriver
    image:
      imageId: sha256:631fc0c6acbdef40bd9e9b1546b898388c3207ad373ea055f191580910ee02db
      repository: armory/clouddriver-armory
      tag: 2022.09.14.17.01.20.master
    vcs:
      repo:
        orgName: armory-io
        repoName: clouddriver-armory
        type: github
      sha: 8a0b6b34ffcdd4b0b749a0452a339282bedda7eb
  deck-armory:
    baseService: deck
    image:
      imageId: sha256:e8ce4457d60adffc5fc7d095425d333dfdaafac023323df2082e443ed788d27e
      repository: armory/deck-armory
      tag: 2022.12.12.16.45.20.master
    vcs:
      repo:
        orgName: armory-io
        repoName: deck-armory
        type: github
      sha: b24f68d6c44a5ad222aeb4f57f15a5c3e1b36082
  dinghy:
    image:
      imageId: sha256:c66fe5557f46f25b5e7b2a7c75f1993a748ca4dfff1470f636836152ced5fcc3
      repository: armory/dinghy
      tag: 2022.10.27.16.41.18.master
    vcs:
      repo:
        orgName: armory-io
        repoName: dinghy
        type: github
      sha: 505015ac9d2539290af87e9a1e234827905db645
  echo-armory:
    baseService: echo
    image:
      imageId: sha256:98460903c28b36772490718709b4cc88d0138b8b87d7a0a2e15613ab06455f2a
      repository: armory/echo-armory
      tag: 2022.12.14.22.23.34.master
    vcs:
      repo:
        orgName: armory-io
        repoName: echo-armory
        type: github
      sha: 2519f61ced1411bbe49cf981f9ae49b43f9ed4f4
  fiat-armory:
    baseService: fiat
    image:
      imageId: sha256:23285eb60dd84ce39a180c33bd974de7cdfd66c4e3b99092ab07f505c8953750
      repository: armory/fiat-armory
      tag: 2022.12.15.16.58.24.master
    vcs:
      repo:
        orgName: armory-io
        repoName: fiat-armory
        type: github
      sha: 74f38812ea704138674bf76c36ee1b7a1515e45f
  front50-armory:
    baseService: front50
    image:
      imageId: sha256:1d0dc4de0f08c948bddf1ad1f760981b4f5fff063d19e8853f82227c3880296b
      repository: armory/front50-armory
      tag: 2022.07.08.02.40.47.master
    vcs:
      repo:
        orgName: armory-io
        repoName: front50-armory
        type: github
      sha: b8ea85489ae8ba7f09e93573a364e9ba4c3512fb
  gate-armory:
    baseService: gate
    image:
      imageId: sha256:67b4e14ca1adece5011a8425777bf61630fe0fabeb64d0ef9ab64d47c1ac965e
      repository: armory/gate-armory
      tag: 2022.11.17.22.19.35.master
    vcs:
      repo:
        orgName: armory-io
        repoName: gate-armory
        type: github
      sha: f22b9d124867bb865860e9419a1c9a1e6e910cd6
  igor-armory:
    baseService: igor
    image:
      imageId: sha256:d9498ab90b76c900d305a9cedd2fd65d5a8423a4893f0a5705f78e38b2c00c2f
      repository: armory/igor-armory
      tag: 2022.09.14.16.39.54.master
    vcs:
      repo:
        orgName: armory-io
        repoName: igor-armory
        type: github
      sha: 3c9dd843c3eddbfaa529f054b2df73de938391ca
  kayenta-armory:
    baseService: kayenta
    image:
      imageId: sha256:275d58704d7d6f14397f17ccc954108940d9f5937c02e886494206f6b50edea0
      repository: armory/kayenta-armory
      tag: 2022.12.15.22.14.36.master
    vcs:
      repo:
        orgName: armory-io
        repoName: kayenta-armory
        type: github
      sha: af685ffc6580e162fd05f247fe07586cc679c10e
  orca-armory:
    baseService: orca
    image:
      imageId: sha256:a07f498bda756da05e413592a551fe9fb3cba8c6ef17c2c7520636cfe1f6a586
      repository: armory/orca-armory
      tag: 2022.04.04.16.22.09.master
    vcs:
      repo:
        orgName: armory-io
        repoName: orca-armory
        type: github
      sha: 238fc61ed93dd33702377f756455b44fff5acb5d
  rosco-armory:
    baseService: rosco
    image:
      imageId: sha256:0239102d0be64253c18df1bba7657b6eb9cdb4a2c2f40d2a4b2fc32b0c7629ed
      repository: armory/rosco-armory
      tag: 2022.07.20.21.06.26.master
    vcs:
      repo:
        orgName: armory-io
        repoName: rosco-armory
        type: github
      sha: fb245283577bd8d2d699c331a17c98011e260afe
  terraformer:
    baseService: null
    image:
      imageId: sha256:0d0ed4a42d4362f96caf4dc45814abaf1e858b5df1f972135f07e62f8f12df6a
      repository: armory/terraformer
      tag: 2022.08.15.08.23.24.master
    vcs:
      repo:
        orgName: armory-io
        repoName: terraformer
        type: github
      sha: 06274aea2918f7e47222856537224de91c9cf542
