services:
  orca-armory:
    baseService: orca
    image:
      imageId: sha256:68a090f4078f2512686875fcc05a840151b9bb662123caa56b755c35a7c8d5a6
      repository: armory/orca-armory
      tag: 2021.05.04.01.20.01.master
    vcs:
      repo:
        orgName: armory-io
        repoName: orca-armory
        type: github
      sha: 6b80ae69bade7c01d0ec7ed524da2b2518fb648b
