services:
  clouddriver-armory:
    baseService: clouddriver
    image:
      imageId: sha256:53c3a9a2ef3f1dccaea6feb2538f18d1bb4952d13663c07bd39be6c3f2e17796
      repository: armory/clouddriver-armory
      tag: 2022.07.08.15.29.56.release-2.27.x
    vcs:
      repo:
        orgName: armory-io
        repoName: clouddriver-armory
        type: github
      sha: 486a1499f23a44460feb3fd5a979e8fb5c0e1fa1
  deck-armory:
    baseService: deck
    image:
      imageId: sha256:2da0eb2b853470eba9e5e49b09be96835406411d1ecfddc585930b6951480648
      repository: armory/deck-armory
      tag: 2022.06.14.17.54.03.release-2.27.x
    vcs:
      repo:
        orgName: armory-io
        repoName: deck-armory
        type: github
      sha: d0a4c0b534877e8b38d9dc03c2dc4a683c289a64
  dinghy:
    baseService: null
    image:
      imageId: sha256:c24fa4ab0ace8a0728627dd679133a7d1521d98dd5480d9035f860d2dec6452e
      repository: armory/dinghy
      tag: 2022.01.25.21.39.56.release-2.27.x
    vcs:
      repo:
        orgName: armory-io
        repoName: dinghy
        type: github
      sha: ee2e7f8b9778741dae1a5571cb47ac6c76c51d81
  echo-armory:
    baseService: echo
    image:
      imageId: sha256:6f9730bde6b6a7543a4fb3b8cb3cee66fb20d325dd25104ac7085f7ff0cec828
      repository: armory/echo-armory
      tag: 2022.04.27.04.59.09.release-2.27.x
    vcs:
      repo:
        orgName: armory-io
        repoName: echo-armory
        type: github
      sha: 824b6c3cbaeea32df6c2a83e70287168587fb951
  fiat-armory:
    baseService: fiat
    image:
      imageId: sha256:8ccfd59105696c416ff92efe2d5939f6a4f497a405df749ef86f5e6922faf811
      repository: armory/fiat-armory
      tag: 2022.07.08.15.33.53.release-2.27.x
    vcs:
      repo:
        orgName: armory-io
        repoName: fiat-armory
        type: github
      sha: e4acd6a010d9bd810a09ba083a6b7ce26d153e37
  front50-armory:
    baseService: front50
    image:
      imageId: sha256:0babc2d6bd0fdc371a25e7c3aa9109869842097bdbc612ff2dcc25922d623b2f
      repository: armory/front50-armory
      tag: 2022.07.08.15.40.22.release-2.27.x
    vcs:
      repo:
        orgName: armory-io
        repoName: front50-armory
        type: github
      sha: 3fce07c181aa2a8a4c7e8edcd7a34d3432251b3e
  gate-armory:
    baseService: gate
    image:
      imageId: sha256:aeec241c5a3e0938b13d3580ce771c3a8dd67557e1e62c65ace44163802b7510
      repository: armory/gate-armory
      tag: 2022.07.06.17.25.58.release-2.27.x
    vcs:
      repo:
        orgName: armory-io
        repoName: gate-armory
        type: github
      sha: dd569b4abc4d54f446c43a58f3b58640505baf32
  igor-armory:
    baseService: igor
    image:
      imageId: sha256:f7f9bcf2e49a4c962db1c915ead704498f302e3e6cdd10dcd823eb45fae3f075
      repository: armory/igor-armory
      tag: 2022.07.08.15.30.30.release-2.27.x
    vcs:
      repo:
        orgName: armory-io
        repoName: igor-armory
        type: github
      sha: e9399998f26517271acda3c083a6c4c0f2d38fa2
  kayenta-armory:
    baseService: kayenta
    image:
      imageId: sha256:41fd13c65e6f31cd68671852a620d69ed3559daad78280b2428c9cdb180cf591
      repository: armory/kayenta-armory
      tag: 2022.07.08.15.31.16.release-2.27.x
    vcs:
      repo:
        orgName: armory-io
        repoName: kayenta-armory
        type: github
      sha: 62cb8fcdb89b30da5c9060bda912d40ca56a167f
  orca-armory:
    baseService: orca
    image:
      imageId: sha256:ec2b8e8adaf25f4a8b301bfce4c2f430110d96c7a4a88e76848a2294d2daff2d
      repository: armory/orca-armory
      tag: 2022.07.08.15.37.09.release-2.27.x
    vcs:
      repo:
        orgName: armory-io
        repoName: orca-armory
        type: github
      sha: 35f409991c1fa245fcecb77fb637b7bdd93de754
  rosco-armory:
    baseService: rosco
    image:
      imageId: sha256:fa5df14cb20ce0c3293306b261c1fc622e30c632790d3a3706a909b747d0fa52
      repository: armory/rosco-armory
      tag: 2022.07.11.18.14.32.release-2.27.x
    vcs:
      repo:
        orgName: armory-io
        repoName: rosco-armory
        type: github
      sha: ecdccb279800afaed8695588071e656631895225
  terraformer:
    baseService: null
    image:
      imageId: sha256:c82aee5fd9e681d7e37a909f7c58244bb8ab1e52975df31a4b887b88d5a7e63c
      repository: armory/terraformer
      tag: 2022.05.09.21.43.08.release-2.27.x
    vcs:
      repo:
        orgName: armory-io
        repoName: terraformer
        type: github
      sha: 97ea226de97509838a0216cea2b1643bcb568188
