services:
  clouddriver-armory:
    baseService: clouddriver
    image:
      imageId: sha256:cf09677d71e1586392f63a5997ee469d46c04d864ba1cb9c5cd59fbfcce16b0d
      repository: armory/clouddriver-armory
      tag: 2022.03.17.00.42.25.release-2.27.x
    vcs:
      repo:
        orgName: armory-io
        repoName: clouddriver-armory
        type: github
      sha: 654b83c9a075712595de7273cecb03668924e257
  deck-armory:
    baseService: deck
    image:
      imageId: sha256:b7078114834b140e5883b4efbbcfd98db72ebb06170101d4c196978400962ceb
      repository: armory/deck-armory
      tag: 2022.03.17.18.45.23.release-2.27.x
    vcs:
      repo:
        orgName: armory-io
        repoName: deck-armory
        type: github
      sha: 6da861c96ef96fa8320889668ad57b600ea53a0b
  dinghy:
    baseService: null
    image:
      imageId: sha256:c24fa4ab0ace8a0728627dd679133a7d1521d98dd5480d9035f860d2dec6452e
      repository: armory/dinghy
      tag: 2022.01.25.21.39.56.release-2.27.x
    vcs:
      repo:
        orgName: armory-io
        repoName: dinghy
        type: github
      sha: ee2e7f8b9778741dae1a5571cb47ac6c76c51d81
  echo-armory:
    baseService: echo
    image:
      imageId: sha256:137647000c68d3a6ca57e9c8ad7f823ed51a4631b9567c7c5447ffa39c36a87c
      repository: armory/echo-armory
      tag: 2022.03.17.19.30.11.release-2.27.x
    vcs:
      repo:
        orgName: armory-io
        repoName: echo-armory
        type: github
      sha: 93cd6081f76dfa8dd3b18c8956b6978dbcdee836
  fiat-armory:
    baseService: fiat
    image:
      imageId: sha256:c821f33fc5ce9d70c6a249a3b3566b98a0d7a4349267bbc53b9d3e016089f4a0
      repository: armory/fiat-armory
      tag: 2022.03.17.19.30.05.release-2.27.x
    vcs:
      repo:
        orgName: armory-io
        repoName: fiat-armory
        type: github
      sha: a49b0cc4f842caafa6b78b975cfae02f6a0ac1b0
  front50-armory:
    baseService: front50
    image:
      imageId: sha256:51a4e4b3eb28fd5d58d2d97ebdfe07793abe197b2ffc785461ed490e635d916a
      repository: armory/front50-armory
      tag: 2022.03.04.04.42.14.release-2.27.x
    vcs:
      repo:
        orgName: armory-io
        repoName: front50-armory
        type: github
      sha: cdb90f4dc3d55c2a5150a3e573b1862cef93816b
  gate-armory:
    baseService: gate
    image:
      imageId: sha256:a987d3e66fe80f6f3fcf02e6874928e1ffe8e92383be3c7f56ee172efa4f81e1
      repository: armory/gate-armory
      tag: 2022.03.17.19.31.32.release-2.27.x
    vcs:
      repo:
        orgName: armory-io
        repoName: gate-armory
        type: github
      sha: 9895b83d6f5856a039233c77586582c791db4876
  igor-armory:
    baseService: igor
    image:
      imageId: sha256:97517609cb63cb945d5cf162e9cf1d453c04fad72689dd5b08f9a5bbcfac1f08
      repository: armory/igor-armory
      tag: 2022.03.17.00.42.20.release-2.27.x
    vcs:
      repo:
        orgName: armory-io
        repoName: igor-armory
        type: github
      sha: 2ad862864655afa32e63d32db7db0246edc6ea2b
  kayenta-armory:
    baseService: kayenta
    image:
      imageId: sha256:f43330f30abcf97d06c4ff29ac13dad76800d1682cb4b1ff1d8bd62f85f2f909
      repository: armory/kayenta-armory
      tag: 2022.02.22.23.20.32.release-2.27.x
    vcs:
      repo:
        orgName: armory-io
        repoName: kayenta-armory
        type: github
      sha: 800b14c9162cc0f486f4e7f510f87ec8db9b5e98
  orca-armory:
    baseService: orca
    image:
      imageId: sha256:b20913335eabf47351fddc6e6c482676148f71c68f9d3a614da08d6d5929c18a
      repository: armory/orca-armory
      tag: 2022.03.17.00.40.15.release-2.27.x
    vcs:
      repo:
        orgName: armory-io
        repoName: orca-armory
        type: github
      sha: 88c44710211d05fb1c5fce3f96dafd76748e1e91
  rosco-armory:
    baseService: rosco
    image:
      imageId: sha256:e7f89ead7d159eb6f30bd51299008f98f0863eea96a4864c4ae9e2e74c11a395
      repository: armory/rosco-armory
      tag: 2022.03.17.09.09.46.release-2.27.x
    vcs:
      repo:
        orgName: armory-io
        repoName: rosco-armory
        type: github
      sha: 19385f47391a54823402a682a759fb0a913fd2bd
  terraformer:
    baseService: null
    image:
      imageId: sha256:a76d25ba71acadec6fda2e606c6c98d04b67fa5a104d425e4f44864aacb1c843
      repository: armory/terraformer
      tag: 2022.03.17.09.30.55.release-2.27.x
    vcs:
      repo:
        orgName: armory-io
        repoName: terraformer
        type: github
      sha: 842c8f521bcb715a1569049fa1efed8879baaaec
