services:
  clouddriver-armory:
    baseService: clouddriver
    image:
      imageId: sha256:ffa5aa66724251fe7505532ae3a842b23d07d29f36d753678d831c2581426fa5
      repository: armory/clouddriver-armory
      tag: 2022.03.10.18.01.19.release-2.27.x
    vcs:
      repo:
        orgName: armory-io
        repoName: clouddriver-armory
        type: github
      sha: 2af0e77ea1daf1bd36d56be271391fd1fa3b3a3a
  deck-armory:
    baseService: deck
    image:
      imageId: sha256:aad9f72602d436ffc7fd1928cf171139ad85c8a8a29f4fec25adfc449ff7cc5d
      repository: armory/deck-armory
      tag: 2022.01.21.15.46.38.release-2.27.x
    vcs:
      repo:
        orgName: armory-io
        repoName: deck-armory
        type: github
      sha: ea911f8927180bb5223f3c6149005568111ad294
  dinghy:
    baseService: null
    image:
      imageId: sha256:c24fa4ab0ace8a0728627dd679133a7d1521d98dd5480d9035f860d2dec6452e
      repository: armory/dinghy
      tag: 2022.01.25.21.39.56.release-2.27.x
    vcs:
      repo:
        orgName: armory-io
        repoName: dinghy
        type: github
      sha: ee2e7f8b9778741dae1a5571cb47ac6c76c51d81
  echo-armory:
    baseService: echo
    image:
      imageId: sha256:883e902ef668cb062518cfea7aa2cb264e20e45bae3ae39a3c50fe88c0a21228
      repository: armory/echo-armory
      tag: 2022.02.22.22.28.48.release-2.27.x
    vcs:
      repo:
        orgName: armory-io
        repoName: echo-armory
        type: github
      sha: aa794fa58437bbaae6b3f7c32f4844e5da937c92
  fiat-armory:
    baseService: fiat
    image:
      imageId: sha256:4731d1407ca6695d64310abf65aac8e2d870347d8314c32126a5c9c8993a004a
      repository: armory/fiat-armory
      tag: 2022.03.02.19.04.28.release-2.27.x
    vcs:
      repo:
        orgName: armory-io
        repoName: fiat-armory
        type: github
      sha: e285a77d97d73304e3a1f75fd67c736eac804a37
  front50-armory:
    baseService: front50
    image:
      imageId: sha256:51a4e4b3eb28fd5d58d2d97ebdfe07793abe197b2ffc785461ed490e635d916a
      repository: armory/front50-armory
      tag: 2022.03.04.04.42.14.release-2.27.x
    vcs:
      repo:
        orgName: armory-io
        repoName: front50-armory
        type: github
      sha: cdb90f4dc3d55c2a5150a3e573b1862cef93816b
  gate-armory:
    baseService: gate
    image:
      imageId: sha256:f2355d0c910c627399357177cb9e03508504c203531c82b05d412fc6ca5d8668
      repository: armory/gate-armory
      tag: 2022.02.22.22.40.58.release-2.27.x
    vcs:
      repo:
        orgName: armory-io
        repoName: gate-armory
        type: github
      sha: f4f1b1c0511d7d20e948541eceb020112acc9f52
  igor-armory:
    baseService: igor
    image:
      imageId: sha256:d46042429f586410b2cb1996a4bcdfc391cad09df567c0d708c095b0e2c70b58
      repository: armory/igor-armory
      tag: 2022.02.22.22.48.00.release-2.27.x
    vcs:
      repo:
        orgName: armory-io
        repoName: igor-armory
        type: github
      sha: 97986b3554e3501507989335e73618a832357f71
  kayenta-armory:
    baseService: kayenta
    image:
      imageId: sha256:f43330f30abcf97d06c4ff29ac13dad76800d1682cb4b1ff1d8bd62f85f2f909
      repository: armory/kayenta-armory
      tag: 2022.02.22.23.20.32.release-2.27.x
    vcs:
      repo:
        orgName: armory-io
        repoName: kayenta-armory
        type: github
      sha: 800b14c9162cc0f486f4e7f510f87ec8db9b5e98
  orca-armory:
    baseService: orca
    image:
      imageId: sha256:e5fc3caabd2b928bdce69dccb2b4222534c2fd9d9a45f5b61f23cad58ba55cf6
      repository: armory/orca-armory
      tag: 2022.02.22.23.00.20.release-2.27.x
    vcs:
      repo:
        orgName: armory-io
        repoName: orca-armory
        type: github
      sha: 4fe016e9539cfae5cf79b39888227afc11a5741b
  rosco-armory:
    baseService: rosco
    image:
      imageId: sha256:0d31df8f72b3940e094124ae3ef584c0e7f428d6900e8fcfacdca769b86f46fb
      repository: armory/rosco-armory
      tag: 2022.03.08.09.08.54.release-2.27.x
    vcs:
      repo:
        orgName: armory-io
        repoName: rosco-armory
        type: github
      sha: c4d895daa717ce4ce6b87d92949d14ab9b1e1791
  terraformer:
    baseService: null
    image:
      imageId: sha256:ecf35a806daa139349aad78d9b702db9871807c2a4998a1b215cf708b9c13e14
      repository: armory/terraformer
      tag: 2021.12.20.16.50.16.release-2.27.x
    vcs:
      repo:
        orgName: armory-io
        repoName: terraformer
        type: github
      sha: 89dd4af83b669d6a12de41611ea0bdf57857dd73
