services:
  clouddriver-armory:
    baseService: clouddriver
    image:
      imageId: sha256:ced627053fbfdc38895607c9dc8432cdd182d1f4f7fb886c64948af72344dbe1
      repository: armory/clouddriver-armory
      tag: 2023.01.11.19.04.16.master
    vcs:
      repo:
        orgName: armory-io
        repoName: clouddriver-armory
        type: github
      sha: 85aeb8ebf69ef9e912574bc0af57619dbd359109
  deck-armory:
    baseService: deck
    image:
      imageId: sha256:97fdd7d2dad4cce7827ae913a5f2c3e09710ad6a7c43515913f6ae6eb55d3a26
      repository: armory/deck-armory
      tag: 2023.02.07.09.40.18.master
    vcs:
      repo:
        orgName: armory-io
        repoName: deck-armory
        type: github
      sha: af26c011045528b2af60ff5f9f6bf775a38afc27
  dinghy:
    image:
      imageId: sha256:cf82dee33077a62da59aed4ddc0cc1fe58a786c8ba0397913e008169d22a3e97
      repository: armory/dinghy
      tag: 2023.02.06.12.26.38.master
    vcs:
      repo:
        orgName: armory-io
        repoName: dinghy
        type: github
      sha: eaf522291c3ce3ff654adac5b46cac2c1dca25a4
  echo-armory:
    baseService: echo
    image:
      imageId: sha256:b86d5cbdff3fa28922d1777c373298c47113ba9dcc8bb5ad23b99c1322eb0508
      repository: armory/echo-armory
      tag: 2023.01.30.16.37.40.master
    vcs:
      repo:
        orgName: armory-io
        repoName: echo-armory
        type: github
      sha: 17198e9b6ad50a96077f8fe861e34528f7e0c38f
  fiat-armory:
    baseService: fiat
    image:
      imageId: sha256:1317b9be6d48d6b57a64b4f2d59f8bd63fb9d1270b817bf0ebc0d9271cb6076c
      repository: armory/fiat-armory
      tag: 2023.02.07.15.34.39.master
    vcs:
      repo:
        orgName: armory-io
        repoName: fiat-armory
        type: github
      sha: d855d9d47fc2772e4beb561d67d3fdd23db6b974
  front50-armory:
    baseService: front50
    image:
      imageId: sha256:1d0dc4de0f08c948bddf1ad1f760981b4f5fff063d19e8853f82227c3880296b
      repository: armory/front50-armory
      tag: 2022.07.08.02.40.47.master
    vcs:
      repo:
        orgName: armory-io
        repoName: front50-armory
        type: github
      sha: b8ea85489ae8ba7f09e93573a364e9ba4c3512fb
  gate-armory:
    baseService: gate
    image:
      imageId: sha256:67b4e14ca1adece5011a8425777bf61630fe0fabeb64d0ef9ab64d47c1ac965e
      repository: armory/gate-armory
      tag: 2022.11.17.22.19.35.master
    vcs:
      repo:
        orgName: armory-io
        repoName: gate-armory
        type: github
      sha: f22b9d124867bb865860e9419a1c9a1e6e910cd6
  igor-armory:
    baseService: igor
    image:
      imageId: sha256:d9498ab90b76c900d305a9cedd2fd65d5a8423a4893f0a5705f78e38b2c00c2f
      repository: armory/igor-armory
      tag: 2022.09.14.16.39.54.master
    vcs:
      repo:
        orgName: armory-io
        repoName: igor-armory
        type: github
      sha: 3c9dd843c3eddbfaa529f054b2df73de938391ca
  kayenta-armory:
    baseService: kayenta
    image:
      imageId: sha256:c4b9f8fc12d74ceb877f4949a6faa02bbbbb607203991b1f57120cdaa126fb90
      repository: armory/kayenta-armory
      tag: 2023.01.24.16.36.23.master
    vcs:
      repo:
        orgName: armory-io
        repoName: kayenta-armory
        type: github
      sha: ff12c509aec3f18ebf6b817dd260be10297ab241
  orca-armory:
    baseService: orca
    image:
      imageId: sha256:a07f498bda756da05e413592a551fe9fb3cba8c6ef17c2c7520636cfe1f6a586
      repository: armory/orca-armory
      tag: 2022.04.04.16.22.09.master
    vcs:
      repo:
        orgName: armory-io
        repoName: orca-armory
        type: github
      sha: 238fc61ed93dd33702377f756455b44fff5acb5d
  rosco-armory:
    baseService: rosco
    image:
      imageId: sha256:40b4a3aace83804cdbf3c0a57842e4fd26511264c820bdb8944d1f82879e0b34
      repository: armory/rosco-armory
      tag: 2023.01.30.16.48.19.master
    vcs:
      repo:
        orgName: armory-io
        repoName: rosco-armory
        type: github
      sha: c33f0242c7ecab8ecfe412da2bc5f5e16684e01c
  terraformer:
    image:
      imageId: sha256:4b445cd48893742a41444f8bdee91cb5ce3ba49d3d9c8d4f1d496b03bc3f3ff6
      repository: armory/terraformer
      tag: 2023.01.05.16.17.47.master
    vcs:
      repo:
        orgName: armory-io
        repoName: terraformer
        type: github
      sha: 418546f57129380e383e62b6178ed582e6d64a93
