services:
  clouddriver-armory:
    baseService: clouddriver
    image:
      imageId: sha256:2de1055597f2eaf1e361510fbd8142ea73da99ea19413852eff1d66f2352ac78
      repository: armory/clouddriver-armory
      tag: 2022.01.19.21.06.53.release-2.26.x
    vcs:
      repo:
        orgName: armory-io
        repoName: clouddriver-armory
        type: github
      sha: 2957f1021447910d60f0f6e9e290988c9b5a11e0
  deck-armory:
    baseService: deck
    image:
      imageId: sha256:fde6b765b92d298bf266ef07d2f5353cbd0683e82edaf44b64c7640679a16ba9
      repository: armory/deck-armory
      tag: 2022.01.25.21.35.37.release-2.26.x
    vcs:
      repo:
        orgName: armory-io
        repoName: deck-armory
        type: github
      sha: 621a865a6130cd00e5bd4dbe2416d0d33be98c37
  dinghy:
    baseService: null
    image:
      imageId: sha256:298a4b593181ef4dd9428bd646a0f08e54a3ba11db8794381323ddfb7c91c25c
      repository: armory/dinghy
      tag: 2022.01.25.21.40.03.release-2.26.x
    vcs:
      repo:
        orgName: armory-io
        repoName: dinghy
        type: github
      sha: a6248311be12901a4fc8f5a3e0fae437b4347ce3
  echo-armory:
    baseService: echo
    image:
      imageId: sha256:f1e0f16da5279101e0f359aa7b88f4b8b9cfdef6aba3b761fa41e744d3b1e4fc
      repository: armory/echo-armory
      tag: 2022.01.25.21.41.06.release-2.26.x
    vcs:
      repo:
        orgName: armory-io
        repoName: echo-armory
        type: github
      sha: 9e35502b409fc4191b3cb87332c4138e9b25edf5
  fiat-armory:
    baseService: fiat
    image:
      imageId: sha256:e6368e7af3432970ac34d9aab0f7de64e8e82f198b08a742445c6fc120a8c2a6
      repository: armory/fiat-armory
      tag: 2021.12.14.23.03.49.release-2.26.x
    vcs:
      repo:
        orgName: armory-io
        repoName: fiat-armory
        type: github
      sha: e46182a670fc9bac7c02f809df7ffe65c89ba148
  front50-armory:
    baseService: front50
    image:
      imageId: sha256:91735a57e61e7629231cfc0ef4a847fe061512e7645acd61580ed3401ae26711
      repository: armory/front50-armory
      tag: 2021.10.01.21.33.11.release-2.26.x
    vcs:
      repo:
        orgName: armory-io
        repoName: front50-armory
        type: github
      sha: 7e14c30538a9b97468aba0360408abf4a06bc0dd
  gate-armory:
    baseService: gate
    image:
      imageId: sha256:84360324b54a34c54f9c6ec2d31894ed9c8df61c6a38f53ef96a46720419f3dc
      repository: armory/gate-armory
      tag: 2021.12.15.17.37.12.release-2.26.x
    vcs:
      repo:
        orgName: armory-io
        repoName: gate-armory
        type: github
      sha: 41c92b2d613e47521c60d2c9036504ff405fbb91
  igor-armory:
    baseService: igor
    image:
      imageId: sha256:c3609288ae9d2d797a5686b64da5686408e7e5f534e3d2d824046b0e61a185a1
      repository: armory/igor-armory
      tag: 2021.10.01.23.09.16.release-2.26.x
    vcs:
      repo:
        orgName: armory-io
        repoName: igor-armory
        type: github
      sha: 889135384533cd723c0a6377a37a7365cf92a8b2
  kayenta-armory:
    baseService: kayenta
    image:
      imageId: sha256:0de5e9ec6a42e1307eb916e78fc7a04f99231877b18c3d75d48655eeba9f1dae
      repository: armory/kayenta-armory
      tag: 2021.10.01.23.43.42.release-2.26.x
    vcs:
      repo:
        orgName: armory-io
        repoName: kayenta-armory
        type: github
      sha: 2403ad86e76898a65939ebdf879bf287fa8b1429
  orca-armory:
    baseService: orca
    image:
      imageId: sha256:ff73b951dc036e504d4ec9a14fabc5802673e6cc488ac9760fa178d07566debd
      repository: armory/orca-armory
      tag: 2021.10.01.23.39.04.release-2.26.x
    vcs:
      repo:
        orgName: armory-io
        repoName: orca-armory
        type: github
      sha: 624af61e6bf75bc92e67a6bef6439f8ae29ec79a
  rosco-armory:
    baseService: rosco
    image:
      imageId: sha256:9236aa749863051fbae80116c1381fd444dfcc0119abad9abb07f7b4e9d59583
      repository: armory/rosco-armory
      tag: 2021.12.13.20.38.49.release-2.26.x
    vcs:
      repo:
        orgName: armory-io
        repoName: rosco-armory
        type: github
      sha: cbb42562fad6583e6efcb24a7378cb6fd84668f0
  terraformer:
    baseService: null
    image:
      imageId: sha256:fc028dea9f74e1dd5f21f9c70d6469180796ab2be72c084c5eac83b05b8a2881
      repository: armory/terraformer
      tag: 2021.12.20.16.50.22.release-2.26.x
    vcs:
      repo:
        orgName: armory-io
        repoName: terraformer
        type: github
      sha: 0cded7056eeecbb85a70a1b94fe1ce83613295bf
