services:
  clouddriver-armory:
    baseService: clouddriver
    image:
      imageId: sha256:0d3e704da45a039baa0f06e6f447dcd8f44ef85b43811d6ff4275651be029634
      repository: armory/clouddriver-armory
      tag: 2021.07.26.15.42.30.master
    vcs:
      repo:
        orgName: armory-io
        repoName: clouddriver-armory
        type: github
      sha: 6ab195fce1233629f520cd1091d7435a5f8cd689
  deck-armory:
    baseService: deck
    image:
      imageId: sha256:fff8bda795ad1d5cf808894a090f8b457d1db551c6ac89f301989abd020288f6
      repository: armory/deck-armory
      tag: 2021.08.03.22.07.46.master
    vcs:
      repo:
        orgName: armory-io
        repoName: deck-armory
        type: github
      sha: 4cbe144e7eb94eb784c2df0f552df50ddac08051
  dinghy:
    baseService: null
    image:
      imageId: sha256:fff91a3d1888052faa1fc6fb72b677d6c563c76567266f206abe0aff7c757aab
      repository: armory/dinghy
      tag: 2021.07.19.20.54.25.master
    vcs:
      repo:
        orgName: armory-io
        repoName: dinghy
        type: github
      sha: de5233ec95845206e20f9b969426c2bf35c98d73
  echo-armory:
    baseService: echo
    image:
      imageId: sha256:5a02a90391dcf62bdbdfa07f52ae59207249f8b73bc947ab5010d2d4b279184a
      repository: armory/echo-armory
      tag: 2021.07.30.21.15.08.master
    vcs:
      repo:
        orgName: armory-io
        repoName: echo-armory
        type: github
      sha: a876ddb7ab2723b2989165c799783ffbb95b4d59
  fiat-armory:
    baseService: fiat
    image:
      imageId: sha256:5af68599d66021042b45df8b2c6339e26736d4749767b0911619d5aa3f6dd79a
      repository: armory/fiat-armory
      tag: 2021.08.04.22.53.02.master
    vcs:
      repo:
        orgName: armory-io
        repoName: fiat-armory
        type: github
      sha: b51256d70c00653497f0b2f215fcd3721b1a1cdb
  front50-armory:
    baseService: front50
    image:
      imageId: sha256:f0ed70eaf9906353924fed76ec832ffb1fd01f970908198fcb095e95fcbe279e
      repository: armory/front50-armory
      tag: 2021.08.03.20.54.51.master
    vcs:
      repo:
        orgName: armory-io
        repoName: front50-armory
        type: github
      sha: 2786323b4013866838b668cacb72a77c5e282f05
  gate-armory:
    baseService: gate
    image:
      imageId: sha256:8875b89a66434d9513c79ebac05347b6237b6229baaa9307d68cb686800fe26b
      repository: armory/gate-armory
      tag: 2021.07.28.18.09.32.master
    vcs:
      repo:
        orgName: armory-io
        repoName: gate-armory
        type: github
      sha: 727765cf9524bd47d6f3c03c0543bf8776d8ce77
  igor-armory:
    baseService: igor
    image:
      imageId: sha256:f0ef46ef6319225772a5093a7f48a9b7d374f4eac6c9e9f6591537846d1aafbb
      repository: armory/igor-armory
      tag: 2021.08.04.20.27.21.master
    vcs:
      repo:
        orgName: armory-io
        repoName: igor-armory
        type: github
      sha: d60f65a0449370a2cab25137664f498903607924
  kayenta-armory:
    baseService: kayenta
    image:
      imageId: sha256:5e25846ae11eac966f0a2381513288b8e316095ad5ebe55713e0aa3c48edae86
      repository: armory/kayenta-armory
      tag: 2021.08.04.20.48.44.master
    vcs:
      repo:
        orgName: armory-io
        repoName: kayenta-armory
        type: github
      sha: c107287f820e68e8692511243a9c02e5a8569279
  orca-armory:
    baseService: orca
    image:
      imageId: sha256:b5f70ef720603c6938795511ecb66a64eb19d1cd3ffe048efdc556c9d7a94d56
      repository: armory/orca-armory
      tag: 2021.08.04.21.01.54.master
    vcs:
      repo:
        orgName: armory-io
        repoName: orca-armory
        type: github
      sha: 2d6b2691ae8c3b249953eb7f4d97f673d8107242
  rosco-armory:
    baseService: rosco
    image:
      imageId: sha256:61aeeb7a68daec6f07e28bd1ecd97a8ecb6ef5bc6ca5eb142917db9747dc2603
      repository: armory/rosco-armory
      tag: 2021.07.21.22.38.02.master
    vcs:
      repo:
        orgName: armory-io
        repoName: rosco-armory
        type: github
      sha: 42103e208c025e1cba26bc818dd17139458689f4
  terraformer:
    baseService: null
    image:
      imageId: sha256:647ebb06bdbf9bcd84ffd4f95ad790e9236eaea0258883427d62a9b1fd82940c
      repository: armory/terraformer
      tag: 2021.07.15.17.11.22.master
    vcs:
      repo:
        orgName: armory-io
        repoName: terraformer
        type: github
      sha: 717efc9563cee20cb9c37068db976d9598461e1e
