services:
  clouddriver-armory:
    baseService: clouddriver
    image:
      imageId: sha256:1d4ac7e9d937289301af1a6603fb087f56913a63626e6b01fab03c53917fedb4
      repository: armory/clouddriver-armory
      tag: 2022.03.21.23.58.58.release-2.27.x
    vcs:
      repo:
        orgName: armory-io
        repoName: clouddriver-armory
        type: github
      sha: a4ecbb3f5909fc27031f83e9e6bc5eb0bd48e412
  deck-armory:
    baseService: deck
    image:
      imageId: sha256:3eb83c0a9b05b515ab291c635d117b812530d3e68854ec72b62ca78a1eb73d58
      repository: armory/deck-armory
      tag: 2022.03.23.23.24.53.release-2.27.x
    vcs:
      repo:
        orgName: armory-io
        repoName: deck-armory
        type: github
      sha: e1207937e2987406ba6d9f07b9c1bf683f57e3da
  dinghy:
    baseService: null
    image:
      imageId: sha256:c24fa4ab0ace8a0728627dd679133a7d1521d98dd5480d9035f860d2dec6452e
      repository: armory/dinghy
      tag: 2022.01.25.21.39.56.release-2.27.x
    vcs:
      repo:
        orgName: armory-io
        repoName: dinghy
        type: github
      sha: ee2e7f8b9778741dae1a5571cb47ac6c76c51d81
  echo-armory:
    baseService: echo
    image:
      imageId: sha256:eef602d7e8a3155222e2185b62ad13affadc25c96cd6f8fb794d54ed3c365008
      repository: armory/echo-armory
      tag: 2022.03.21.23.36.17.release-2.27.x
    vcs:
      repo:
        orgName: armory-io
        repoName: echo-armory
        type: github
      sha: daf883e2d1f572df0dddc7452366d81f291f2b36
  fiat-armory:
    baseService: fiat
    image:
      imageId: sha256:89eba3716c1b9bee5d4ffa54255f14992a02f88c758a2ca7a8ad9926172e8a1b
      repository: armory/fiat-armory
      tag: 2022.04.01.22.56.49.release-2.27.x
    vcs:
      repo:
        orgName: armory-io
        repoName: fiat-armory
        type: github
      sha: e26b2c10bccf5a82473482efda2fc710430b803a
  front50-armory:
    baseService: front50
    image:
      imageId: sha256:8620cba347e6e2240a16bd503c0495baad22be16ec902a9a2f3cab2bb7fce6ff
      repository: armory/front50-armory
      tag: 2022.03.23.20.39.36.release-2.27.x
    vcs:
      repo:
        orgName: armory-io
        repoName: front50-armory
        type: github
      sha: 3c3fffda543a818ab6f2ab385783adb4c58c7aaa
  gate-armory:
    baseService: gate
    image:
      imageId: sha256:7a0131995a7b861ad64dce8503ef8356b9b3eff9067aef3a978b420c64c2d1e0
      repository: armory/gate-armory
      tag: 2022.03.21.23.37.11.release-2.27.x
    vcs:
      repo:
        orgName: armory-io
        repoName: gate-armory
        type: github
      sha: e6cae79cd53c2a1bb696db29cbed9ab268b46613
  igor-armory:
    baseService: igor
    image:
      imageId: sha256:23f6c5064317475302d0884cf2b56d578728db12e63ca69ec34f627e88b0e41e
      repository: armory/igor-armory
      tag: 2022.03.21.23.37.53.release-2.27.x
    vcs:
      repo:
        orgName: armory-io
        repoName: igor-armory
        type: github
      sha: 0ba6c07c3f7ac5a4eaff1a3e4d13d334c90a2341
  kayenta-armory:
    baseService: kayenta
    image:
      imageId: sha256:f43330f30abcf97d06c4ff29ac13dad76800d1682cb4b1ff1d8bd62f85f2f909
      repository: armory/kayenta-armory
      tag: 2022.02.22.23.20.32.release-2.27.x
    vcs:
      repo:
        orgName: armory-io
        repoName: kayenta-armory
        type: github
      sha: 800b14c9162cc0f486f4e7f510f87ec8db9b5e98
  orca-armory:
    baseService: orca
    image:
      imageId: sha256:af86d5d0fabbc1dc22b2212696deb1c68e95bc051b5872c58115d9a4ec171670
      repository: armory/orca-armory
      tag: 2022.03.21.18.58.38.release-2.27.x
    vcs:
      repo:
        orgName: armory-io
        repoName: orca-armory
        type: github
      sha: 0f0798aca2763853efd40f40b7a29bd877ed2808
  rosco-armory:
    baseService: rosco
    image:
      imageId: sha256:9111bf302d35633a467f5cd7f3ace9218a4e53229672993a45b0c0e41e5610f5
      repository: armory/rosco-armory
      tag: 2022.03.21.23.40.32.release-2.27.x
    vcs:
      repo:
        orgName: armory-io
        repoName: rosco-armory
        type: github
      sha: f12518df92f4922d2b75c7c9ee14f7d489da2680
  terraformer:
    baseService: null
    image:
      imageId: sha256:a76d25ba71acadec6fda2e606c6c98d04b67fa5a104d425e4f44864aacb1c843
      repository: armory/terraformer
      tag: 2022.03.17.09.30.55.release-2.27.x
    vcs:
      repo:
        orgName: armory-io
        repoName: terraformer
        type: github
      sha: 842c8f521bcb715a1569049fa1efed8879baaaec
